### ISSUE TITLE
content: BFCache hitrate calculation has problems

### ISSUE THREAD

**Issue by fergald** [GoogleChrome/web.dev#10262]
### What page(s) need to be updated?

Provide a list of URLs.

https://web.dev/bfcache/#measuring-your-bfcache-hit-ratio

### Why is this update needed?

The condition code  `if (event.persisted || navigationType == 'back_forward' ) {` over-counts cache misses.

There are some scenarios when a pageload occurs with `navigationType == 'back_forward'` but it was not a cache miss

- reopening the browser after shutdown or reopening a closed tab, navigationType will be the same value as before the browser/tab was closed. It's possible that tab discarding for memory reclaiming will do this too but I haven't tested.
- duplicating a tab. The duplicated tab will have the same value as the original

There are some tricks with session cookies that can catch some of these. Soon, the not-restored reasons API will be make cache misses unambiguous.

https://docs.google.com/document/d/1xOb7-DRb67pW87f8pqPvBrR_K-CcQoWoR7x4OujKb-Y/edit?resourcekey=0-UjypvAfixnJriizckv9nGA#heading=h.7xtxyqntzqe7

has more discussion and code samples.

@malchata @tunetheweb @philipwalton

**Comment by tunetheweb** [comment]
Well technically those two scenarios are a replay of a previous bfcache miss right? So, yes a slight over-counting but then arguably other page navigations are over counted in this way too. It would be really nice if [the navigation timing api treated bfcache navigations as full navigations](https://github.com/w3c/navigation-timing/issues/184), and also similar for restores (also in that issue) to avoid having to consider all these edge cases in each separate implementation :-(

I'll assign this to me and update this, along with the not-restored reasons API.

**Comment by tunetheweb** [comment]
> It's possible that tab discarding for memory reclaiming will do this too but I haven't tested.

Actually it [looks like Discarded pages do not emit the PageShow event](https://developer.chrome.com/blog/page-lifecycle-api/) so don't think these will be counted.

**Comment by fergald** [comment]
> > It's possible that tab discarding for memory reclaiming will do this too but I haven't tested.
> 
> Actually it [looks like Discarded pages do not emit the PageShow event](https://developer.chrome.com/blog/page-lifecycle-api/) so don't think these will be counted.

Am I misreading that diagram? The *only* way to get to `pageshow` is via FROZEN. DISCARD goes back to "Broswser starts loading the page" which does *not* go through `pageshow`. That can't be right.

I think that diagram should be

![image](https://github.com/GoogleChrome/web.dev/assets/4255463/31fed8b7-434d-4b82-97d6-9b266de93c6f)

If you agree, let's open an issue for that.

**Comment by fergald** [comment]
> Well technically those two scenarios are a replay of a previous bfcache miss right? So, yes a slight over-counting but then arguably other page navigations are over counted in this way too. 

I guess it depends on whether you're thnking about *navigations* or *pageloads*. So yes, there's no navigation when you restart your browser or dup a tab but there are of pageloads. For the most-part, people are measuring pageloads (since it's hard/impossile distinguish them without the not-restored-reasons API).

My concern is that sites that are simple and have no BFCache blockers should be able to measaure a hit-rate of 100%. We can see from telemetry that including these miscounts gives your site a max hit-rate of about 95% which could be a source of confusion.

**Comment by tunetheweb** [comment]
Looks like we have an issue for that:
https://github.com/GoogleChrome/developer.chrome.com/issues/5123

Also another tweak we should do at the same time:
https://github.com/GoogleChrome/developer.chrome.com/issues/5062

@philipwalton do you have the original source file for this diagram so we can make edits?
And do either of you know who “owns” the page lifecycle API and can confirm both these issues and best fix for them?

**Comment by philipwalton** [comment]
> @philipwalton do you have the original source file for this diagram so we can make edits?

Yep, I can share it to you.

> And do either of you know who “owns” the page lifecycle API and can confirm both these issues and best fix for them?

Nobody who worked on the API back in 2018 still works on Chrome (other than me). The [most recent commit](https://github.com/WICG/page-lifecycle/commit/5ea95470f9709bed5c01c91d1c5d4e03a40530e5) to the spec updated the editor to Scott Haseley, though I don't think Scott has made any contributions and I'm not aware that there is an active "owner".

For some context about why the `DOMContentLoaded`, `load`, and `pageshow` were not in the loading phase of the original diagram:

The first iteration of the Page Lifecycle API did have `LOADING` as a distinct state, but there were issues with that, e.g. because a page can be loaded in either the `ACTIVE`, `PASSIVE`, or `HIDDEN` state, and we didn't want it to be possible to be in two states at once, so we decided that "loading" and "unloading" would be considered "phases" that would be separate from states. The purpose of the state diagram was to show what events could trigger a state change, and since `DOMContentLoaded` and`load` don't trigger state changes they weren't included, and `pageshow` was only included in cases where it triggers a change from `FROZEN`.

Also, FYI, when the Page Lifecycle API was being worked on, the team had hopes of vastly simplifying the number of number of events that would fire (e.g. deprecate `unload` entirely, and maybe we don't need `pagehide` if we have `freeze`) as well as the order of events (e.g. maybe [`visibilitychange` should fire before `pagehide`](https://github.com/whatwg/html/issues/3957) instead of after for consistency) but for a number of reasons no progress was made on these changes, and as a result the diagram actually got more complicated rather than less complicated (e.g. compare the [2018 version](https://github.com/GoogleChrome/web.dev/assets/326742/dfa7d2e9-4080-428b-b9ee-395ad4ec8f1e) with the [2022 version](https://github.com/GoogleChrome/web.dev/assets/326742/1a329c5b-740b-424f-909e-ca10a924a82b)).

Anyway, given that we weren't able to remove `unload` and `pagehide` from the state/event diagram, I agree that for balance it would be helpful to add them—if for nothing else then to explain the order in which they fire (`DOMContentLoaded`, `load`, `pageshow`) and clarify that `DOMContentLoaded` and `load` don't re-fire after a bfcache restore.

**Comment by fergald** [comment]
@philipwalton thanks for that.

So do we have a conclusion on whether pageshow fires when reloading after DISCARD? I hope so, otherwise I expect pages to break.

**Comment by philipwalton** [comment]
> So do we have a conclusion on whether pageshow fires when reloading after DISCARD? I hope so, otherwise I expect pages to break.

Yes, `DOMContentLoaded`, `load`, and then `pageshow` all fire (in that order) after a discard, just as they do for normal loads.

**Comment by dstmarthe** [comment]
Thanks for raising this. We’re moving to a new platform and so we’ll fix this over there. I’ve moved the issue to our new tracker and you can see it at https://issuetracker.google.com/u/1/issues/298903676
