### ISSUE TITLE
Improve the look of the site on 240px displays.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#1118]
**Is your feature request related to a problem? Please describe.**
The site should look nicer on feature phones. Currently most pages are "ok" but could be improved. The /measure page is pretty broken.

**Describe the solution you'd like**
Write better CSS!

**Comment by jblair87** [comment]
Hi @robdodson , I would like to help out with this. A few suggestions off the bat for the Measure page are attached in the screenshots below. The numbered list is aligned to be consistent with numbered lists on the learning path pages (ie. /fast). The four categories center are stacked and center aligned. Please let me know if you would like me to move forward and/or have any additional suggestions.
![Measure-web-dev-categories](https://user-images.githubusercontent.com/13993320/61585517-e924f400-ab2a-11e9-8cff-124815771598.png)
![Measure-web-dev-list](https://user-images.githubusercontent.com/13993320/61585518-e924f400-ab2a-11e9-90d6-4760fd3b9d2d.png)

**Comment by alexandersandberg** [comment]
I did a quick audit of /measure to help with this issue. I created a graphic showing some problems that I found. Keep in mind that this was only tested in the latest Safari on macOS, so there might be other issues.

I found some issues at 320px as well, not just 240px. I made a graphic summarizing what I found, with some suggestions for fixes (see enlarged image). I also listed everything below, for everyone's convenience.

![Summary of suggestions for /measure](https://user-images.githubusercontent.com/35671299/61585378-759adb00-ab5a-11e9-813b-67fe51b2a455.jpg)

### Summary of issues with suggestions
**320px and below**
* Date for last audit and 'View Report'/'Download Report' links needs to be stacked
* Results in metrics table are the overflowing container. Some alternative fixes:
  1. Reduce margin between title and result (seconds)
  2. Add ellipsis to overflowing text (probably not a good idea)
  3. Stack results (probably best idea, since needed (?) on <320px)
* Audit list probably needs to stack severity level, audit message, and guide link
  * Will need new table headers though since these won't make sense if stacked. Can probably just keep 'Impact' one, since it's the only one you interact with (sorting). Others are not essential (?).

**240px and below**
* Tiny 'web.dev' logo. It can be fixed by pushing the search icon and the 'SIGN IN' link to the right, if possible (looks like it, since the margin to the right is unnecessarily wide).
* Buttons need to be stacked which requires fixing the margins; remove left and add top.
* Score card gauges will either need new, smaller titles or (what I think is the best solution) just change `min-width` on `.lh-score-card` to `100%` at breakpoint xxsmall and below.

---

I'd love to help out with this if you need a hand. Let me know!

**Comment by alexandersandberg** [comment]
@jblair87 Funny how we both commented on this at the same time. 😄

**Comment by jblair87** [comment]
@alexandersandberg I know! None the issues we addressed overlapped. In reference to the audit list, I noticed the category of the audit is hidden at max-width 840px. I suggest this column is displayed and instead one of the other columns are hidden or combined. The Guide is a hyperlinked version of the Audit. The Guide/Audit can break to the next line or fit in the same row. 
![Measure-web-dev-audit](https://user-images.githubusercontent.com/13993320/61585835-cd721b80-ab33-11e9-9f57-d2030125b999.png)

I have attached an image below of a solution for 
"Date for last audit and 'View Report'/'Download Report' links needs to be stacked"
![Measure-web-dev-last-audit](https://user-images.githubusercontent.com/13993320/61585844-e975bd00-ab33-11e9-8cfa-26dadab25c6f.png)

**Comment by alexandersandberg** [comment]
@jblair87 That's a great idea! Here are some other ideas—some of which I prototyped—in an attempt at 320px and below.

![Examples of fixes for audit list layout at 320px and 240px device widths](https://user-images.githubusercontent.com/35671299/61587414-63389580-ab8a-11e9-971a-b2bbc8619c09.jpg)

### Conclusions from this attempt
* I thought we could convert the long link into an icon instead, and keep the 'Audit' column as an explanation of where the link leads us. This, however, does not leave any room for the 'Category' column, as you proposed
* The 'Impact' levels have been shortened to only the first character. This may or may not be enough information for the user to determine the severity; while the color helps us identify it pretty quickly, people not being able to identify the colors—for whatever reason—will only have 'H', 'M', and 'L' to rely on
* Another solution would be to remove the 'Impact' level from each row, and instead group the rows depending on severity level, and use a header ('High', 'Medium', or 'Low') for each group. This might lead to unnecessarily complex implementation though, and you won't be able to sort it (without complex UX)
* Despite these fixes, it still doesn't look great at 240px, so we might as well stack the content at 320px as well

However, I still like the idea of using icons for the long links at ~500px (depending on the breakpoints already used) and below—provided that the 'Audit' column is still shown—even though we stack the content.

**Comment by alexandersandberg** [comment]
I took the liberty to prototype a solution for an audit list with stacked content, becasue what better way do you spend your calm Sunday morning? ☺️🍵

![Proposal for audit list with stacked content inside rows](https://user-images.githubusercontent.com/35671299/61587685-f1af1600-ab8e-11e9-97ae-b542d3d34c3a.jpg)

I think this achieves many of the things we want here:
* Clear descriptions of the audits
* Clear and accessible severity level indications, using both text and colors to convey their message
* Interaction affordance; the arrows clearly states that there's an interaction here

There's also room to add the corresponding 'Category' above each audit description, if needed.

**Comment by jblair87** [comment]
@alexandersandberg I really like the use of the arrows here. I think this is a great solution.

**Comment by robdodson** [comment]
oh my gosh this is so great!!! thank you both for doing this 😍

apologies for my slow response, I'm in training workshops until Thursday. I can start implementing these suggestions later this week. 🙌

**Comment by alexandersandberg** [comment]
@robdodson Great! I would love to brainstorm these changes further if you need any feedback or input, so feel free to reach out! 😊

**Comment by alexandersandberg** [comment]
Did some more work on this. I've divided it up into headings to make it easier to read.

## Share buttons blocking content
On blog post pages, the two 'share' buttons at the bottom right corner take up a little too much space vertically.

### Possible solution(s)
I think the best solution would either be to make them smaller, or as I prototyped below—see image 1—place them horizontally instead. Since we read from side-to-side, placing them horizontally will block less content from being readable.

![propsal of new button placement](https://user-images.githubusercontent.com/35671299/61824837-48527380-ae5f-11e9-8b96-6c5e3c6888fd.jpg)
_Image 1. Prototype of placing 'share' buttons on blog posts horizontally instead of vertically._

## Difficulties noticing page load when using the menu
When using the sidebar menu at 240px, the menu blocks the whole page. This means that, when clicking menu items to load new pages, it can be difficult to know when the new page has loaded (see GIF 1 for a demonstration).

This is not always the case however, since you do get a blue loading bar at the top, notifying the users about the progress of the page load. But when you have a fast connection speed, you don't really notice this bar.

![using sidebar menu to open new pages at 240px device width](https://user-images.githubusercontent.com/35671299/61825186-18f03680-ae60-11e9-9989-a5c529ab6e0d.gif)
_GIF 1. Demonstration of using sidebar menu to load new pages at 240px._

### Possible solution(s)
A solution would be to not span the open sidebar across the whole viewport. This is the behavior at 320px and above. See image 2 for a prototype. This is not the perfect solution, but it's easier to notice the page load. This means the user can click to the side of the sidebar to close the menu as well.

![a prototype of what the sidebar would look like with the new behavior](https://user-images.githubusercontent.com/35671299/61826353-87ce8f00-ae62-11e9-9a75-841e50dfec3b.jpg)
_Image 2. Proposal for new open menu behavior below 320px._

Another solution would be to automatically close the sidebar once the new page has loaded, but this might be hard to implement, I'm not sure. I think this would be the best solution though, since—at the moment—the menu is of no use after the requested page has loaded.

## Uneven lists at 320px and below
At (and including) 320px and below, some lists' dots and numbers appear a bit uneven with the text. Image 3 shows a few examples of this.

This applies to—from what I've seen so far—regular unordered (`<ul>`), regular ordered (`<ol>`) lists, as well as grid lists (`<ul class="w-unstyled-list w-grid-list">`, and there might be an ordered one?).

![a few examples of uneven lists](https://user-images.githubusercontent.com/35671299/61828226-77b8ae80-ae66-11e9-89c7-eb6bf6ee6692.jpg)
_Image 3. Some examples of uneven lists that I found._

### Possible solution(s)
"Simply" align the dots with the text.

## Missing resources amount on collection cards
Below 320px, the 'x resources' text on collection cards are missing due to limited space. See image 4.

![comparison between 240px's and 320px's collection cards](https://user-images.githubusercontent.com/35671299/61828548-3d034600-ae67-11e9-83b7-6d6cebe7e799.jpg)
_Image 4. Comparison between collection cards on 240px and 320px._

### Possible solution(s)
I think it's good to keep the purple 'Collection' title for each card, which means that the 'x resources' text has to either be made smaller, or—as I prefer—make it stack underneath the card's title.

---

I've only had time to test this in Safari on macOS and iOS yet, so there might be more issues in other browsers.
