### ISSUE TITLE
Clarify capitalization of origin trial

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#1184]
Web.dev is inconsistent with the deliberate and long-standing practice of the group that manages origin trials in that it capitalizes the phrase whereas the group that manages them does not. The philosophical basis of this is given by the definition of proper noun in one of my reference books. "A _proper noun_ (emphasis theirs) identifies a specific member of a class." In the estimation of that group an origin trial is a class, not a member of a class. If you read their [developer's guide](https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/developer-guide.md) you'll see that they have been deliberate and consistent about this.

I'm not writing this bug to debate the point. I am writing to point out that materials that will some day be ported to web.dev follow the OT team's practice, not just their own, but everything I've personally edited over the last few years. One set of documents, either web.dev or Web Fundamentals and origin trials will need to be changed. It may be that web.dev is the small set of files to change.

**Comment by jpmedley** [comment]
This is also the practice I've followed in the beta release posts since taking it over.

**Comment by robdodson** [comment]
Removed the writing label because that's used by our bot to indicate the lifecycle phase that a piece of content is in. Maybe I can annotate that in a way that it's clear that it's a bot label...

I'm fine updating the term "origin trial" to be consistent with whatever the prior art is. @mfriesenhahn any objections?

**Comment by jpmedley** [comment]
(Sidebar: the usage guide should provide some guidance around classes of things versus instances of things. I'm using the linguistic meaning of those terms, not the CS meaning.)

**Comment by mfriesenhahn** [comment]
Here's my vote for how to proceed:

**Do now**
- Un-cap all instances of "origin trial" across the site in a new PR.

**Do later**
- Forego the distinction between classes and instances and instead include the distinction between proper and common nouns, which contains the former distinction and is more widely known.
- Include that guidance by pointing to the GDDSG. (This would be part of a larger reworking of the Grammar page to focus on exceptions to the GDDSG rather than its greatest hits, which I'd like to talk through with the content team before executing.)

**Comment by jpmedley** [comment]
I should less vague. I'm stating that guidance should clarify that the distinction between a common noun and a proper noun is the distinction between classes and instances. It states explicitly what my grammar books and probably most others only imply. I have two reasons for proposing this:

* The frequency with which I've had to explain that being the subject of the a piece of writing does not make something a proper noun.
* Defining one in terms of the other makes the distinction clearer to engineers than it otherwise would be.

**Comment by robdodson** [comment]
@mfriesenhahn @jpmedley is this issue still active or can we close it? I know Jeff added an include for origin trials but I wasn't sure if that fully addressed this issue.

**Comment by mfriesenhahn** [comment]
Defer to @jpmedley about whether capping of "origin trial" has been fixed. If so, I think the handbook stuff can be dealt with separately.

**Comment by jpmedley** [comment]
As I recall Jeff's include is correct. If it's in the handbook, this can be closed.

**Comment by mfriesenhahn** [comment]
I'll open a separate PR to add this and a couple other things to the word list. I'll go ahead and close this one.
