### ISSUE TITLE
The term "code splitting" is hyphenated inconsistently throughout the site

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/web.dev#1364]
We use both "code splitting" and "code-splitting" through web.dev articles, and (as far as I can tell) there's no pattern to when we hyphenate vs. when we don't.

- https://web.dev/reduce-javascript-payloads-with-code-splitting
- https://web.dev/code-splitting-suspense
- https://web.dev/route-level-code-splitting-in-angular

Looking at other sites on the internet, they do it too, so I'm not sure which one is correct.

- https://webpack.js.org/guides/code-splitting/
- https://rollupjs.org/guide/en/#code-splitting
- https://reactjs.org/docs/code-splitting.html

My preference would be for "code splitting" when used as a noun or a verb, and "code-splitting" (or "code-split") when used as an adjective, but either way, we should standardize and add our preferred form to the [word list](https://web.dev/handbook/word-list/).

**Comment by mathiasbynens** [comment]
To me the pattern has always been as follows (not just for code splitting but for any English term):

- no hyphen when used as a noun: "to achieve code splitting", "by enabling code splitting"
- hyphen when used as a verb: "by code-splitting the bundles"

Not using a hyphen in the latter example is confusing, since it could reasonably be read as "by code [pause] splitting the bundles".

**Comment by philipwalton** [comment]
Hmmm, I'd not heard about hyphenating when a compound word was used as a verb, but looks like that's true based on these links (which also mention using a hyphen to avoid ambiguity):

- https://www.proofreadnow.com/blog/bid/29485/Grammar-Usage-Compound-Verbs
- https://www.quora.com/What-are-the-rules-for-hyphenating-verbs-in-English
- https://www.grammarbook.com/punctuation/hyphens.asp

But in the web.dev articles I listed above, we use hyphenation inconsistently even when "code splitting" is used as a noun. We should standardize that.

**Comment by robdodson** [comment]
@mfriesenhahn @jpmedley for their thoughts

**Comment by mfriesenhahn** [comment]
Ha, I just added this to my to-dos last week. I'm good with Matthias' approach, though I might suggest that the handbook encourage writers to avoid the verb form because it's a little awkward. For example, "split the code bundles" seems better than "code-split the bundles." This is aligned with our approach for other cases like _round trip_.

**Comment by mfriesenhahn** [comment]
Fixed in #1378. @jpmedley, if you could give it a once over, that'd be great!

**Comment by jpmedley** [comment]
Here's my take:

   - Discourage the verb form.
   - No hyphen when it is noun form.
   - Hyphen when in adjective form. (Example: "The code-splitting process
   is ...")

By the way, this is the standard procedure for all two word noun
constructions.
Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by mfriesenhahn** [comment]
Thanks, Joe! The PR matches what you recommend. Is everybody cool with that?

**Comment by mfriesenhahn** [comment]
@philipwalton, are you OK with this solution? If so, we can merge this PR.

**Comment by philipwalton** [comment]
Yeah, SGTM!
