### ISSUE TITLE
Expandable content component

### ISSUE THREAD

**Issue by Snugug** [GoogleChrome/web.dev#1454]
**Is your feature request related to a problem? Please describe.**
Critical to some of the PWA content, especially #1349, is the ability to display content in an expandable form, allowing for a collapsed preview of content and more details view that can be expanded out from it.

**Describe the solution you'd like**
A component that can take either a title and a short description, both of which Markdown/basic formatting should be allowed in, in the main area and, when clicked on, expands either below or out revealing details that can contain any amount or Markdown/formatted content.

**Describe alternatives you've considered**
Footnotes, linking to different sections of a document

**Additional context**
Hard blocker for #1349

**Comment by robdodson** [comment]
@mfriesenhahn can you share a link to the material design component that does this? Maybe we can base something off of that?

**Comment by mfriesenhahn** [comment]
Here it is: https://material.io/design/communication/writing.html#principles

I could perhaps mock something up after a bit of discussion. Also, I might suggest putting some boundaries around the formatting and content this thing can accommodate to prevent problematic uses.

**Comment by mfriesenhahn** [comment]
I threw [this mock](https://codepen.io/mfriesenhahn/full/ExYvEBv) together as a starting point for discussion. It adds a bit of markup and some styles to the existing `detail` component.

**Notes:**
- I tried to make the styles as flexible as possible:
  - The heading can take `h1`-`h6` or `p`.
  - There's an optional content preview, as requested.
  - Like the existing `detail` component, you can throw whatever you want in the panel.
- I adjusted the styling to make the salience more appropriate:
  - I've added color and states to make it more immediately obvious that this is interactive.
  - I've increased the surrounding white space.
  - Since the heading uses `h1-h6` or `p` elements, it inherits their styles, ensuring that it has the appropriate salience for its position in the hierarchy.
- @robdodson, my assumption is that the `detail` element will provide assistive tech users the semantics they need, so the **Read more** button is really just an aid for sighted users. So, I made it a pseudo element and set it to `speak: none`. Not confident about that though.
- I'm imagining the short code for this would look something like:
  ```md
  {% Detail 'heading', 'optional-heading-level', 'optional-state' %}
  
  {% DetailPreview %}
    <preview content>
  {% endDetailPreview %}
  
  <panel content>
  
  {% endDetail %}
  ```
  
  For example, if you wanted a `Detail` component that's open by default with an `h3` heading and a preview, you'd do:
  ```md
  {% Detail 'How to optimize your images', 'h3', 'open' %}
  
  {% DetailPreview %}
    Optimizing your images is super important...
  {% endDetailPreview %}
  
  Optimizing your images is super important for making your site load quickly. Here are some strategies...
  
  {% endDetail %}
  ```

**Comment by robdodson** [comment]
@Snugug would this component meet your needs? If so we can do a PR for it.

**Comment by Snugug** [comment]
Hey all!

Yah I think this would work great for us! The only thing I hope we can change from the provided preview is the 25 word maximum in the content preview. We're writing specific short descriptions, 1-3 sentences, and the longest one currently is ~34 words. In general I'm a big believer that, to [quote Karen McGrane](https://www.slideshare.net/KMcGrane/developing-successful-content-management-solutions/44-MOBILE_WEB_MOBILE_WEBSITE_APPS) "truncation is not a content strategy" and we should avoid it as much as possible.

**Comment by mfriesenhahn** [comment]
Oh, there's no actual character limit. I was just lifting/adapting content from the Material Design site as placeholder text. The preview text and the content in the panel would be functionally independent. That said, I agree that truncation is ungood, but I do think concision is a virtue, particularly with a progressive disclosure control 😄

@robdodson, do you want to set up the short code, or do you want me to give it a try?

**Comment by robdodson** [comment]
Chatted with @mfriesenhahn today and he's going to take a shot at implementing this.

**Comment by Snugug** [comment]
Hey all! Checking on the status.

**Comment by mfriesenhahn** [comment]
Hey, sorry for the delay! Been occupied by other things. I can prioritize this tomorrow or Monday, if that works.

**Comment by Snugug** [comment]
That'd be great, thanks!
