### ISSUE TITLE
Add route base code-splitting

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#1505]
**Describe the solution you'd like**
To keep the site nice and snappy, we should only load JavaScript that the user needs for the current route. This means a lot of the stuff for /measure could be deferred (though preloaded since we know that route is popular).

**Comment by samthor** [comment]
My 2c on this is just to create perhaps three different entry points:

* signed in normal page
* logged out normal page
* Measure page (since it has the bulk of our code requirements)

These entry points do very little aside import further JS. We give the three of them to Rollup and let it *magically* come up with a graph of code, which we just ship as `type="module"`, importing missing content as users change states between the three possibilities above.

**Comment by samthor** [comment]
Some thoughts: we could load our CSS per-module (in JS) and have them blit it out on use. This way we just use Rollup and our CSS becomes giant JS variables.

I'll do a proper writeup today, just some thoughts.

**Comment by samthor** [comment]
We now need to add injecting CSS in JS and potentially any other "splits" we want (right now it's measure vs everything else). This will involve telling our build script how to render Sass so we can inline CSS.

**Comment by robdodson** [comment]
sgtm!
