### ISSUE TITLE
content: Improve guidance in critical-request-chains post

### ISSUE THREAD

**Issue by mfriesenhahn** [GoogleChrome/web.dev#1608]
The `critical-request-chains` post in the `lighthouse-performance` collection is currently pretty light on details, which seems likely to make it difficult for inexperienced devs to understand what critical request chains are, how they affect performance, and how to optimize them.

**Comment by robdodson** [comment]
Shall I assign this to @kaycebasques to decide on an author?

**Comment by mfriesenhahn** [comment]
Up to you. Didn't want to assign since we've decided further updates to audit posts will be deferred till after CDS.

**Comment by robdodson** [comment]
k

**Comment by kaycebasques** [comment]
I updated the beginning of the doc to link to Ilya's comprehensive critical rendering path docs. This is the lazy fix, but it's good enough for now.

**Comment by chrisblakley** [comment]
I know this issue is closed, but this weekend I've been fighting with some critical request chain issues and I think one part of this article that could be improved is clarifying in more detail this bullet:

```
Minimize the number of critical resources: eliminate them, defer their download, mark them as async, and so on.
```

In my case, simply adding an `async` attribute did not clear the script in question from the critical request chain list. I usually defer my scripts, but this one needs to run early, but has no dependencies/dependents so I figured async would solve the issue, but no luck. Not trying to troubleshoot here, but wanted to provide some feedback to improve the instructions in this article.

Thanks!
