### ISSUE TITLE
Add styles for blockquote elements

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1650]
See https://github.com/GoogleChrome/web.dev/pull/1624/files#r333776944 for context.

**Comment by devnook** [comment]
Context: 

In order to get quote styled, you have to put it in <blockquote class="w-blockquote">.
As Rob said, this is kinda silly. We should make it so it just styles the blockquote element generically.

This said, we have uses of blockquote without "w-blockquote" class, e.g.: http://penguin.termina.linux.test:8081/handbook/markup-media/

Should we therefore keep styling on the class or change the use of blockquote in other cases?

**Comment by robdodson** [comment]
> This said, we have uses of blockquote without "w-blockquote" class, e.g.: https://github.com/GoogleChrome/web.dev/blob/master/src/site/content/en/handbook/markup-media/index.md

Oh good point. I think we should generically style the `blockquote` element and change the markup we're using in the handbook page you linked to.

It's also worth noting that it's not a good practice to style tags directly, but we do it because markdown outputs plain tags. We could also think about scoping our markdown styles using a class. For example:

```scss
.article-has-markdown {
  blockquote {
    ...
  }
}
```

We'd add the `.article-has-markdown` class to the top of our posts. That way if we want to use `blockquote` somewhere else, we don't have to undo the styles we've added.
