### ISSUE TITLE
TypeError: axe is not a function

### ISSUE THREAD

**Issue by brightpixels** [GoogleChrome/web.dev#1651]
**Describe the bug**
https://web.dev/accessibility-auditing-react

**To Reproduce**
1. Generate reacr app using create-react-app (CRA)
2. Replace `ReactDOM.render(<App />, document.getElementById('root'));` with the following
````
if (process.env.NODE_ENV !== 'production') {
  import('react-axe').then(axe => {
    axe(React, ReactDOM, 1000);
    ReactDOM.render(<App />, document.getElementById('root'));
  });
} else {
  ReactDOM.render(<App />, document.getElementById('root'));
}
````

3. `npm start`

**Expected behaviour**
Broken app with error in console and page: `TypeError: axe is not a function`

** Fix that has worked for me
`axe.default(React, ReactDOM, 1000);` instead of `axe(React, ReactDOM, 1000);`

**Screenshots**
https://ibb.co/82znTRy

**Comment by robdodson** [comment]
Hi @brightpixels, I think you may want to file this in [the react-axe repo](https://github.com/dequelabs/react-axe).

**Comment by michaeljaltamirano** [comment]
@robdodson Hi Rob, I stumbled on this issue because I was going to file an issue/PR myself just now. I see that you noted that this issue should be filed in the `react-axe` repo, but the syntax in that repo is `var axe = require('react-axe')`. On the `web.dev` page `import('react-axe').then(axe => {})` returns a module, for which there's a `default` value you have to access, owing to how webpack lazy-loading returns the module:

<img width="522" alt="Screen Shot 2020-06-29 at 3 10 42 PM" src="https://user-images.githubusercontent.com/13544620/86051276-c679ab80-ba1a-11ea-875d-0d71b1745f09.png">

I think it would be appropriate to merge in #2116 because the [current page](https://web.dev/accessibility-auditing-react/) is using inaccurate syntax. What do you think?
