### ISSUE TITLE
Previous and next article links don't always make sense.

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1691]
https://github.com/GoogleChrome/web.dev/pull/1658#discussion_r335611967

Because we've linked to the Next.js and older CRA content from web.dev/react, when you get to the end of the Next.js content the "next article" will be the intro of the CRA collection.

**Comment by robdodson** [comment]
In other parts of the site, we treat each "topic" kind of like a chapter in a book. So in the [Secure](web.dev/secure) or [Accessible](web.dev/accessible) sections, they flow into one another and that's a good thing.

In the Fast section, it's maybe a little less helpful because you go from optimizing images right into optimizing JS, even though they're pretty different topics.

In one of our early prototypes we treated each topic as its own module:
![image](https://user-images.githubusercontent.com/1066253/67032646-d89ffd80-f0c8-11e9-8ac9-ec460ddcdabe.png)

And then each module had its own table of contents page:
![image](https://user-images.githubusercontent.com/1066253/67032676-ebb2cd80-f0c8-11e9-8057-3922b8707139.png)

I think it may make sense to do a round of design to revisit this concept. It would allow us to better break up big sections like /fast, and also create more clear signposting when someone is at the end of a module and about to  start another one.

**Comment by robdodson** [comment]
#1914 is also related.

**Comment by kaycebasques** [comment]
@robdodson the old module design does seem to make more sense

**Comment by kaycebasques** [comment]
This is a P2 problem that we can close for now.
