### ISSUE TITLE
Add support for tags.

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#1808]
> In a book index, which shares underlying theory with tags, one of these would have 'see the other` instead of a page number. Synonyms are a must for indexes and tags because it's a way to account for a reader having a different term in their head than what's used in the article.

--- @jpmedley

https://github.com/GoogleChrome/web.dev/pull/1726/files#r340843948

**Comment by robdodson** [comment]
Can you explain a bit more what you'd like to see here?

**Comment by kaycebasques** [comment]
* When browsing tags, users might search for different synonyms. Some might search for `vr` whereas others might search for `virtual-reality`, so it'd be good to support both. This is what Joe was getting at.
* Suppose author A only tags their post with `vr`, whereas author B only tags their post with `virtual-reality`. Without a tag synonym infrastructure, when a user browses the posts tagged with `vr`, they won't actually see our full list of VR content.
* We therefore need some sort of infrastructure that will enable us to specify that a certain tag is synonymous with other tags. So when a user visits the `vr` tag they'll also see the posts that are tagged with `virtual-reality`.

First structure that comes to mind:

```
tags: {
  vr: {
    synonyms: [
      'virtual-reality'
    ]
}
```

**Comment by jpmedley** [comment]
VR is probably the worst example of this. This is one of the few paper conventions that translates directly to the web, but never has been.

**Comment by kaycebasques** [comment]
@jpmedley am I describing the situation correctly? Please elaborate if not.

**Comment by jpmedley** [comment]
You've captured it.

**Comment by robdodson** [comment]
> When browsing tags, users might search for different synonyms. Some might search for vr whereas others might search for virtual-reality, so it'd be good to support both. This is what Joe was getting at.

At the moment we don't have designs for tag search, though [we do have designs for tags UI](https://github.com/GoogleChrome/web.dev/issues/1188#issuecomment-548195437). That UI assumes a fixed set of tags.

Currently we use [Algolia](https://www.algolia.com/) to power the search bar at the top of the site. Aloglia is super powerful and we're just using a tiny fraction of what it provides. It might be possible to offload the synonym stuff to it somehow.

> Suppose author A only tags their post with vr, whereas author B only tags their post with virtual-reality. Without a tag synonym infrastructure, when a user browses the posts tagged with vr, they won't actually see our full list of VR content.

I was thinking we would want to prevent this by making the tag grammar fixed and only allowing an author to use a predefined tag that's in the system. Initially this could be enforced with linting, and eventually a CMS if we decide to go that route.

**Comment by kaycebasques** [comment]
Sorry, I didn't literally mean search. I just meant when users scan tags. One user might have the `vr` tag in mind while another has the `virtual-reality` tag in mind.

> I was thinking we would want to prevent this by making the tag grammar fixed and only allowing an author to use a predefined tag that's in the system. Initially this could be enforced with linting, and eventually a CMS if we decide to go that route.

This issue came up because Joe wanted to add `vr` and `virtual-reality` (as well as `ar` and `augmented-reality`) to the fixed list in the system (`tags.yaml` or whatever the file is). I pushed back because I don't want to add another manual check to the content review process. Without a tag synonym infrastructure, whenever someone adds a tag like `virtual-reality` I'm going to have to go to `tags.yaml` and manually check if there are any missing synonyms.

**Comment by kaycebasques** [comment]
Check out https://developers.google.com/web/updates/tags for an example of the problem that I'm trying to avoid.

We have an `addtohomescreen` tag: https://developers.google.com/web/updates/tags/addtohomescreen

And an `install` tag: https://developers.google.com/web/updates/tags/install

The list of articles is different.

**Comment by robdodson** [comment]
yeah I understand the problem(s). I'm trying to think through if the proposed solution of adding synonyms would solve them.

Here's a visualization of the tags UI that our agency proposed:
![Tags UI - Desktop Drawer](https://user-images.githubusercontent.com/1066253/68063762-c92bd180-fcd0-11e9-99b0-e7bf4e7d5a2e.gif)

This is displaying a fixed set of tags that the user can filter by. Per your earlier comment:

> Sorry, I didn't literally mean search. I just meant when users scan tags. One user might have the vr tag in mind while another has the virtual-reality tag in mind.

If we had synonyms I don't think it wouldn't help here because we have to choose one thing to display, either vr or virtual-reality.

> Without a tag synonym infrastructure, whenever someone adds a tag like virtual-reality to their post I'm going to have to go to tags.yaml and manually check if there are any missing synonyms that they need to add to their post.

I might be misunderstanding but I think this is true even if you have tag synonyms. If the author is allowed to make up arbitrary tags then you will always need to go back and check the `tags.yaml` to see if their tag should be added as a synonym to some other word. For example, if I write a new post and add the tag `oculus` to it, then someone will need to add it to `tags.yaml` under the `vr` synonyms array.

I think in the near term it may be faster/easier to enforce a fixed tag set, and if someone uses a tag that's not in the set we would lint for that and tell them to find a matching tag in the set or we can decide if the term is unique enough that we should add it. I realize this is probably what webfu does already and your `addtohomescreen` versus `install` example demonstrates that it's pretty easy for it to bitrot if folks aren't vigilant.

As a phase 2 we could look into expanding this to include synonyms. [It seems like Algolia has some functionality around this](https://www.algolia.com/doc/guides/managing-results/optimize-search-results/adding-synonyms/) which we could potentially leverage.

**Comment by kaycebasques** [comment]
> If we had synonyms I don't think it wouldn't help here because we have to choose one thing to display, either vr or virtual-reality.

You could display both. That's what Joe is advocating for, actually. The key thing is that when the user clicks either tag, they get taken to the same list of articles. That's the main problem I care about.

> If the author is allowed to make up arbitrary tags

I'm not proposing that the author can make arbitrary tags on any post. If they want to add a new tag, they'll need to add it to `tags.yaml`. But that doesn't happen that often so I'm not too worried about that. If there is a way to get a bot to leave a special comment when `tags.yaml` is touched, that could help. Or maybe you can update that codeowners file?

The main problem I'm trying to avoid is an author who glances at the tags list, finds `vr`, and just adds that, without checking for synonyms. That's the bitrot problem that will happen and which did happen on /web. 

I guess a low-tech solution would be to add a comment to tags.yaml specifying the synonyms that should be used whenever a given tag is used.

```
---
- 3d
- ar # augmented-reality, xr
...
- augmented-reality # ar, xr
```

**Comment by robdodson** [comment]
> You could display both. That's what Joe is advocating for, actually.

hmmm when the agency was working on that design we discussed avoiding having a long list of tags. The UI on desktop (and especially mobile) may be overwhelming if there's several rows of words and synonyms. At that point it feels like a better UI might be to have a preset list of tags (maybe popular ones) and then a search field that does fuzzy/synonym matching against other tags.

Ultimately I'm not opposed to the idea of synonyms but I'd suggest we do the easy thing first (fixed tag set) because we have designs for it and it's straightforward to implement. It doesn't preclude doing a second phase where we beef it up and add synonym functionality in the future.

**Comment by robdodson** [comment]
Going to consolidate related threads into this one:

- https://github.com/GoogleChrome/web.dev/issues/1188
- https://github.com/GoogleChrome/web.dev/issues/816
- https://github.com/GoogleChrome/web.dev/issues/974

Note, the designs for the proposed tags UI are in the web.dev > Huge >UX and Design > Tags UI Drive directory.

**Comment by jpmedley** [comment]
Here's a example of why we need tag redirects that's better than virtual reality/vr: capabilities and Fugu. Officially we use the word 'capabilities' for this project and it's what appears in all our articles. But everyone involved in it refers to it as Fugu in many public situations while passing out Fugu stickers and Fugu pins. You might argue that this simply requires better message discipline. (1) The people who need to follow it don't report to us. (2) By the time an article lands in the web.dev editing queue, often the messaging cat is already out of the bag.

**Comment by robdodson** [comment]
@kaycebasques one question I have is if we want to work on this while we're still planning the content roadmap stuff. This will be a decently sized engineering project because eleventy doesn't have much built-in support for the kind of tagging we're talking about doing. I have a pretty good understanding of how this would work for a page full of blog posts, but am unclear if we'd want to do anything special for things inside of learning paths. wdyt?

**Comment by jpmedley** [comment]
For what it's worth, it seems like this feature is more useful on the blog
where I don't have IA to convey that articles are related.
Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by kaycebasques** [comment]
@robdodson I suppose tags for the blog posts is the MVP. I think it'd be pretty powerful to have all content on the site properly tagged. It'd be useful for users and also useful for content maintainers because we'll be able to quickly track down all related content. E.g. when an API changes and we need to check if any other docs are affected.

> if we want to work on this while we're still planning the content roadmap stuff

Yes. It feels "orthogonal" to content roadmap. It's one of those features where I'm pretty sure that it will be useful, and shouldn't be affected by content strategy planning. So it's a good candidate for immediate work.
