### ISSUE TITLE
Broken link in staging

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#1866]
The build process for #1865 says staging completed without error, clicking on the actual article returns this:

![image](https://user-images.githubusercontent.com/8204171/68520768-5b8f2080-024f-11ea-9722-d2a3f622d768.png)

**Comment by robdodson** [comment]
I think what's happening is that the article in question if failing to generate because kenji is not in the contributors.json (try running `npm run dev` locally with that PR and you should see the error). I think eleventy is perhaps just logging the error but still building the rest of the site and possibly exiting with a 0 so Netlify thinks the build succeeded.
