### ISSUE TITLE
content: refresh Make Installable Code Lab

### ISSUE THREAD

**Issue by petele** [GoogleChrome/web.dev#2192]
Tracking issue to update existing https://web.dev/codelab-make-installable/

**Comment by kaycebasques** [comment]
@petele I set a target to work on this in March. LMK if that's not going to happen.

**Comment by carolrivero** [comment]
@petele - please provide an update to comment above. thx.

**Comment by petele** [comment]
Not on my priority list for March right now.

**Comment by carolrivero** [comment]
@petele - Should we move this to Apr?

**Comment by petele** [comment]
Can we leave it unassigned date wise until I'm ready to prioritize?

**Comment by kaycebasques** [comment]
I'm going to move this to the Icebox because it sounds like @petele isn't sure whether he has cycles to work on it even in April. No rush on our side and we can always move this back somewhere else if things change. Carol and I just need to keep issue status up-to-date in order to triage all of our content requests.
