### ISSUE TITLE
content: Remove mention of third-party badging [apr 30]

### ISSUE THREAD

**Issue by jschfflr** [GoogleChrome/web.dev#2238]
### What page(s) need to be updated?
https://web.dev/identify-slow-third-party-javascript/#chrome-devtools-third-party-script-badging

### Why is this update needed?
The experiment has been removed:
https://docs.google.com/document/d/1fRNhE_FXfCWwR8zOBkE5J5B6An53Lf0GbQHUB1QSnEI/edit

### What's the deadline?
The change has already landed:
https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/1893080

**Comment by hemakumark** [comment]
As this feature has been sunset, can we hide the documentation from search. 
https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript#chrome_devtools_third-party_script_badging

I was breaking my head since more than 3 hrs why this badge is not showing-up in my developer tools.

**Comment by gmoothart** [comment]
The feature is still mentioned here:
https://developer.chrome.com/blog/new-in-devtools-60/#badges

It would be nice to have an update on the blog post that the feature is no longer available.

**Comment by jblotus** [comment]
Feature also mentioned here: https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript#chrome_devtools_third-party_script_badging

This is what led me to this issue ultimately.
