### ISSUE TITLE
Glitch Suspended on React Guide

### ISSUE THREAD

**Issue by ahmadawais** [GoogleChrome/web.dev#2256]
This [Next.js guide](https://github.com/GoogleChrome/web.dev/blob/master/src/site/content/en/react/performance-as-a-default-with-nextjs/index.md) has a [glitch embed](https://glitch.com/embed/#!/embed/new-next-app?path=index.html&attributionHidden=true) that has been suspended. 

Needs fixing. Let me know if I can help.

**Comment by ahmadawais** [comment]
The [second guide](https://web.dev/route-prefetching-in-nextjs/)'s Glitch doesn't let you view the app, says there's a code error whereas the [third Glitch in there is also suspended](https://glitch.com/embed/#!/embed/nextjs-routing?path=components/MyLink.js&attributionHidden=true).

**Comment by housseindjirdeh** [comment]
Thanks for flagging this @ahmadawais. The two glitches that are currently suspended are:

- new-next-app.glitch.me/
- nextjs-routing.glitch.me/

I've sent an email to Glitch support. I'll let you know as soon as they get back to me (and I would love your help if we need to modify/change things!)

> The second guide's Glitch doesn't let you view the app, says there's a code error

Could you share the link of which glitch is erroring? They seem to be working for me but we can definitely dig in. CC @mihajlija

**Comment by ahmadawais** [comment]
When I try to view the apps, they are all having issues:

![](https://on.ahmda.ws/48bfcd/c)
![](https://on.ahmda.ws/dd7d3c/c)

**Comment by robdodson** [comment]
keep this one open stale bot

**Comment by housseindjirdeh** [comment]
The first app was down due to a system hiccup. Glitch fixed it after I reached out!

All the apps in the second guide (route prefetching) were hitting disk space limits. Looks like the build directory was getting bloated on every build instead of getting replaced.

![image](https://user-images.githubusercontent.com/12476932/79592569-26adb200-80a8-11ea-8611-e443c010babe.png)

I've fixed this and added a `prestart` script to delete the folder before every build. Things should be working fine now :)
