### ISSUE TITLE
content: Wake Lock API case study [Apr 25]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#2267]
* Deadline: 2020 April 25 (hard)
* [Draft](https://docs.google.com/document/d/1BSN7mnGBTiEBk48LU9oeCtlYno9z33wKnos5x77x80o/edit?hl=en)
* Author: @tomayac 
* Reviewer: @jpmedley 

@tomayac if this API isn't supported in other browsers (I can't find MDN or Can I use? articles on the topic) please make sure to mention at the top of the article that this is only supported in Chrome. [Example](https://deploy-preview-2235--web-dev-staging.netlify.com/snap-after-layout/#interoperability).

**Comment by jpmedley** [comment]
It's more complicated than that. Absence on caniuse and MDN may indicate nothing more than being out of date. This is based on [a W3C spec](https://www.w3.org/TR/wake-lock/) that has been around for several years and is edited by employees of other browsers. It could also be that in spite of being W3C, we're just the first to implement it. (Very likely. We do that a lot.) In other words, any statement about this being Chrome-only needs to capture this nuance.

Thomas, if you know for sure that another browser supports this, I'll submit a PR to MDN. Caniuse ingests MDN's compatibility data now, so that will put it on both.

**Comment by jpmedley** [comment]
FYI, Wake Lock is shipping with Promises in Chrome 82. Assuming you're covering that and it's the reason for this article, the deadline is actually 4/25 and it is a hard deadline. (That is one day earlier than the beta release because this needs to be live so that we can link to it from the beta post.)

**Comment by tomayac** [comment]
Work on this has started in this [document](https://docs.google.com/document/d/1BSN7mnGBTiEBk48LU9oeCtlYno9z33wKnos5x77x80o/edit?hl=en) (internal-only, sorry). Acknowledging the hard deadline of April 25.

**Comment by kaycebasques** [comment]
@tomayac please leave a comment in this issue when the draft is ready for @jpmedley's review (I'm presuming Joe is the reviewer because it seems like a Capabilities API)

**Comment by jpmedley** [comment]
@kaycebasques That is correct. I'm emailing you a Fugu spreadsheet.

**Comment by tomayac** [comment]
We're waiting for customer input.
