### ISSUE TITLE
content: Lighthouse guide for CLS

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#2316]
See also https://github.com/GoogleChrome/lighthouse/pull/10427

**Comment by paulirish** [comment]
I am not really sure why we have separate pages for our metrics. One that's general and one with some extra Lighthouse information.
I feel like it's fair to just add a Lighthouse section to the main metric page. (for this and all metrics).

They tend to have the same content anyway.

AFAIK the only reason this hasn't been done yet is because it makes for awkward breadcrumbs. I don't think that's a very compelling reason personally. :)
