### ISSUE TITLE
This is just a question. Why do you guys use 11ty? Would you recommend it to others based on your experience?

### ISSUE THREAD

**Issue by amandeeepsingh** [GoogleChrome/web.dev#2667]

**Comment by robdodson** [comment]
We use it because our team is very familiar with Node and JavaScript so everyone can contribute. It's also used by other google teams (v8.dev, for example) so we have some shared institutional knowledge. Also the tool is very minimal and let's us do whatever we want. I'd recommend it for folks who are building static sites. It really depends on what you're trying to produce :)

**Comment by amandeeepsingh** [comment]
Thanks! @robdodson
