### ISSUE TITLE
content: Web Animations API  [2020-05-27]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#2884]
* [Draft](https://docs.google.com/document/d/1_90aXC73zaYw5Vlh2RGxBcXPI3m1pB2BKfoZnPoiz-o/edit?usp=sharing)
* Author: @una 
* Reviewer: @jpmedley

**Comment by jpmedley** [comment]
Gang, I cleared the milestone since this has to be live on the 27 so we can link to it from the beta post. (Kayce, Una was already aware of this deadline because of an email we exchanged a few weeks ago.)

**Comment by rachelandrew** [comment]
@kaycebasques do you want me to prioritize this over the a11y articles I'm moving?

I'll need access to the draft, which I have requested.

**Comment by una** [comment]
Hi @rachelandrew - the latest is within a branch here called `waapi-stable` -- do you have access? I can put this in a doc for you as well -- whichever you prefer

**Comment by kaycebasques** [comment]
@rachelandrew yes, please prioritize this over the a11y article migrations.

@una it's generally much faster for us to review content in Google Docs but I'll leave it up to Rachel to decide what to do in this particular case.

**Comment by rachelandrew** [comment]
@una yeah editing copy within GitHub is a bit nasty, I went ahead and chucked the markdown into a Google doc. Link is https://docs.google.com/document/d/1sbKoRzn0RE722BCyTtiLqEtAure0sMi3ZdO1VnY-vqg/edit?usp=sharing I hope that's ok but due to timezones I'm wrapping up as some of you are starting work, so I didn't want it left another day before I would look at it.

I made a few suggestions there, one of which was to link to the docs on MDN for some of the methods etc. I note on MDN these are still marked as experimental. When I was working for Mozilla I went through and removed a lot of the experimental flags from CSS properties, as they didn't make a lot of sense. I feel as if this is another case where it no longer should be marked as experimental. The spec is still a WD but there is more than one implementation.

**Comment by kaycebasques** [comment]
@jpmedley is feeling deadline pressure around the Beta release next week and wants to review this one himself to ensure that it goes out in time, so @rachelandrew you're off the hook to review this one

**Comment by rachelandrew** [comment]
was there an issue with the review I did in the doc above?

**Comment by kaycebasques** [comment]
Nope, all good. As I mentioned in our 1:1 doc just now @jpmedley is simply feeling pressure to get the post released in time for the Beta release stuff next week and he was worried that since you're still ramping up on all of our conventions it wouldn't get out in time.

**Comment by una** [comment]
Thank you both for the reviews! Taking both into account.
