### ISSUE TITLE
<web-actions> uses global styles and isn't extensible

### ISSUE THREAD

**Issue by samthor** [GoogleChrome/web.dev#2899]
Our `<web-actions>` is currently only used in the bottom-right of post pages (via `position: fixed`). It also uses global styles (`.w-action` and friends, which aren't used by anything else) and it seems like it just wasn't ported when we migrated all the styles to the elements themselves.

(As an aside, `<web-header>` also uses global styles, but it doesn't render itself and just enhances DOM already on the page.)

This issue/report/proposal replaces #2888 and the (already closed) #2881.

## Current

The element is currently default `display: inline`, but is effectively always `position: fixed` as its first child is `<div class="w-actions">` which is.

It provides a Share (to Twitter, or Web Share where available) button, which shares the current page with its current `document.title` as well as a link to Subscribe (you can choose which of these to support _already_ through an attribute `actions`). Finally, it allows an optional list of authors to share along with the title.

Only the "post" page currently allows Share (it also uses Subscribe), but various other pages allow just Subscribe.

The element is also responsive (showing Subscribe and Share _labels_ on wide screens). This makes it difficult to immediately embed it as a WC elsewhere where we don't know the size it's intended to be displayed at.

## Proposal

Having a single CTA element is quite useful and I'd argue for it to remain as a whole. While it's not common I can see a need for having both share and subscribe shown at once.

* Bring its styles inline and remove `position: fixed`
* Make the pages that currently contain `<web-actions>` wrap it in something like `<div class="w-footer-cta">` which places it in the bottom right
* Add some boolean attributes:
  * "small" or similar, which disables responsive design and always displays as icons without text
  * "extendedOptions" or similar, which adds Facebook/Instagram to the Share options (where Web Share isn't supported)

The element can then be used in both places: inline on web.dev/LIVE, as well as a global element on other pages.

cc @robdodson and @MichaelSolati for discussion

**Comment by robdodson** [comment]
> Our <web-actions> is currently only used in the bottom-right of post pages (via position: fixed). It also uses global styles (.w-action and friends, which aren't used by anything else) and it seems like it just wasn't ported when we migrated all the styles to the elements themselves.
> 
> (As an aside, <web-header> also uses global styles, but it doesn't render itself and just enhances DOM already on the page.)

I haven't looked closely but this may be a good thing if it's preventing FOUC, especially for the header.

> It provides a Share (to Twitter, or Web Share where available) button, which shares the current page with its current document.title as well as a link to Subscribe (you can choose which of these to support already through an attribute actions). Finally, it allows an optional list of authors to share along with the title.

I've been thinking that combining subscribe into this element means it's doing too much. It seems like the only magic that we need a custom element for is to handle the web share magic. I was wondering if:

```html
<web-share type="twitter" authors="foo|bar|baz"></web-share>
```

might be a better option?

> Bring its styles inline and remove position: fixed
> Make the pages that currently contain <web-actions> wrap it in something like <div class="w-footer-cta"> which places it in the bottom right

Would this mean it's no longer a floating action button? I think we want to keep it as a FAB although it would be nice to remove the subscribe button on mobile because having two FABs takes up a lot of visual space. One option would be to make the element `display: inline-block` and then let whichever page is using it decide how to position it. So we could do `position: sticky` where we want it to be a FAB, and other pages could just place it as a regular inline element.

> "extendedOptions" or similar, which adds Facebook/Instagram to the Share options (where Web Share isn't supported)

I'm still unsure about the UX. Here's a screenshot of the share buttons:
![image](https://user-images.githubusercontent.com/1066253/82237272-3c520980-98ea-11ea-9505-22033c6db56d.png)

Is the idea that clicking any of those buttons would open the web share drawer? That seems a bit unexpected because I'd have to pick the social media site again. It seems like this element should only be used when we're using the generic share icon:
![image](https://user-images.githubusercontent.com/1066253/82237695-e7fb5980-98ea-11ea-8d92-a68e3b3f7fdf.png)

Are we sure we want to use web-actions on this page?

**Comment by samthor** [comment]
Rob and I talked about this this morning.

I think our agreement was:

- Remove the subscribe button from this element (possibly break into `web-share` and `web-subscribe`)
- Discuss with UX design whether we need Facebook/Instagram (was this just here because we had space)
