### ISSUE TITLE
The browser that support native payment apps could be other browsers than Chrome

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/web.dev#3022]
**No immediate action required**

In "Android payment apps: developers' guide" **Chrome** is the main subject that handles Android native payment apps, but they can potentially be supported by any browsers. Change "Chrome" to whatever relevant subject when other browsers start to support the functionality.

**Comment by robdodson** [comment]
@agektmr just a heads up that if there's no action to be taken then our stalebot will probably close this issue after 30 days of inactivity. Rather than file a ticket on the repo it may make more sense to create a personal calendar reminder to check-in on this issue after a few months to see if you need to update any docs?

**Comment by agektmr** [comment]
@kaycebasques suggested this but yeah I don't think this would happen within a month. Will remind myself whenever any other browsers start to support native payment apps.
