### ISSUE TITLE
unable to remove save password key from pwa 

### ISSUE THREAD

**Issue by aeshwarya-dev** [GoogleChrome/web.dev#3029]
we want to remove the save password key option from our PWA installer.
i tried using autocomplete=off but it did not work for me. then i tried using onfocus="this.removeAttribute('readonly');"
but i could not remove the save password icon from my installer.

**To Reproduce**
Since it is our company's development, i wont be able to share this.
**Expected behavior**
I want to remove the save password key icon and menu three dots icon from pwa installer.

**Comment by robdodson** [comment]
Hey @aeshwarya-dev 

This repo is for bugs related to the documentation website web.dev, but we don't generally handle browser issues or feature requests here. I think what you're describing sounds like the browser working as intended.

If you'd like to request a change in Chrome's behavior I'd suggest filing a ticket at http://crbug.com/.

**Comment by petele** [comment]
The autocomplete issue is by design, see [this comment](https://stackoverflow.com/questions/3868299/is-autocomplete-off-compatible-with-all-modern-browsers/21348793#21348793) on StackOverflow for more details. It's generally considered bad UX to block users from being able to use their password manager.
