### ISSUE TITLE
content: migrate Lazy loading images and video from web fundamentals

### ISSUE THREAD

**Issue by rachelandrew** [GoogleChrome/web.dev#3100]
#### Provide a brief title for your content proposal

Lazy loading images and video

#### Provide a brief summary of your content proposal

Migrate the guide hosted at https://developers.google.com/web/fundamentals/performance/lazy-loading-guidance/images-and-video 

Needs updating in the light of browser native lazy loading being available, for which there is already content at https://web.dev/native-lazy-loading/ however this article explains how libraries that perform lazy loading work, and how to implement it yourself which is useful as a fallback.

#### Who will be authoring the content?

@rachelandrew

#### What area is your content related to?

Performance

#### What kind of content are you creating?

Guide

**Comment by kaycebasques** [comment]
Our main goal is to redirect [the old page](developers.google.com/web/fundamentals/performance/lazy-loading-guidance/images-and-video) to a single page or section (e.g. `web.dev/fast/#optimize-your-images`) on web.dev.

In this case it's somewhat difficult to redirect to a single page/section because the old page talks about lazy-loading both images and video, but `web.dev/fast` isn't organized that way. I.e. there's a section on optimizing images (`web.dev/fast/#optimize-your-images`), a section for optimizing fonts, and so on. There isn't a good location for talking about images *and* video.

I think lazy loading is important enough to have its own section. We definitely seem to have enough content already for it to be its own section. So I think we should add a lazy loading section to `web.dev/fast`. Like this:

![image](https://user-images.githubusercontent.com/4713486/83688454-4cccda00-a5a2-11ea-9d13-3d7ad9cfdd4a.png)

As mentioned in that screenshot, there are a few existing pages that we'll also want to mention:

* https://web.dev/native-lazy-loading/
* https://web.dev/use-lazysizes-to-lazyload-images/

**Comment by mihajlija** [comment]
> https://web.dev/use-lazysizes-to-lazyload-images/
I'm OK with this being mentioned twice on web.dev/fast (once under "Optimize images", again under this "Lazy loading" section… if it starts happening a lot then we'll have to revisit our IA)

I think it might be better to just move lazysizes to the new lazy loading section. 

Reasoning: Keeping it where it is seems right historically, but in the new IA it doesn't belong there logically. (Should we also put the native lazy loading post in both sections then?)

Since section name is not a part of the post URL, we technically won't break anything. We might be breaking expectations of people who visited the site previously, but if we put the new lazy loading section right after "Optimize images" they should be able to locate the post quickly.

**Comment by rachelandrew** [comment]
I've made a PR for this content (@kaycebasques I can put it into Google docs if required however this is less of a big rewrite and more of a restructuring).

https://github.com/GoogleChrome/web.dev/pull/3176

Questions are mostly about the first article /lazy-loading which has the intro to what lazy-loading is, and other content that didn't seem to fit anywhere else.

1. Should we split out the "what can go wrong" content to another article?
2. There were some credits at the bottom of the article, should I leave them in this first one and maybe refer to the others? Wasn't sure if there was already a case where this was done elsewhere.
3. More generally, I've kept in the details of solutions that work for browsers that don't support Intersection Observer - really IE is all people will care about. Do we want to keep this?
4. I'm not a performance expert, so if there is anything else folk think should be removed, or is now not so great practice please let me know. Likewise if there is anything we really should add.

**Comment by kaycebasques** [comment]
Thanks @rachelandrew, @mihajlija will be reviewing your PR

**Comment by mihajlija** [comment]
@rachelandrew  content reorg suggestions I mentioned yesterday:

1. Removing the section about libraries from the first article and adding sections with appropriate libraries to "Lazy-loading images" and "Lazy-loading video". (All libraries but lazysizes support both images and video.) Reasoning: people who land directly on lazy-loading images (or videos) will have all of the possible options listed right there. Otherwise, they might miss the introduction and not learn about available libraries at all.

2. To accommodate the change above, rewrite the "Implementing lazy loading" section in the first article along the lines: 

> There are a number of ways to implement lazy-loading. Then mention native, writing your own JavaScript, and libraries as options. Keep the note about taking browser support into consideration. Then point readers to detailed guides.

3. Just to clarify my previous suggestion for the section on IE compatible JS solution: Removing the inlined code example and step by step explanation, but keeping the embedded Glitch and maybe linking to [CSS tricks](https://css-tricks.com/the-complete-guide-to-lazy-loading-images/#method-1-trigger-the-image-load-using-javascript-events). De-emphasize the "most compatible way" sentiment and highlight the performance cost.

4. Still in favor of making "what can go wrong" a separate post :)

I'll hold off the full PR review until you incorporate the suggested changes (and any other ideas you might have). I'll just leave some pointers for tidying up markdown while you're at it :)

**Comment by rachelandrew** [comment]
Cool - I'm looking at this today (have already looked at but not committed the earlier suggestion), and that all makes sense. I was a bit worried about tearing it apart too much without getting an extra opinion but that all pretty much aligns to my thinking.
