### ISSUE TITLE
[Pre-event] Update "What to expect" on web.dev/live

### ISSUE THREAD

**Issue by harleenkbatra08** [GoogleChrome/web.dev#3102]
Can we please update the description under "What to expect" to:

Over three days, we'll share quick tips on aspects of modern web development. Each day, **we'll "travel" to a new timezone** to cover a couple aspects and answer your questions.

Update is: I've unbolded "Each day" and removed the 10-20 mins part as one of our sessions may run over to 30-40ish mins.

Thanks!

**Comment by robdodson** [comment]
Updated this to:


Over three days, we'll share quick tips on aspects of modern web development.
Each day, **we'll "travel" to a new timezone** to cover a couple of topics and answer your questions.

I replaced the second use of "aspects" with "topics" because it felt a bit redundant to say it twice. Hope that's ok.
