### ISSUE TITLE
performance audit varies compared to lighthouse tool from webdev tool

### ISSUE THREAD

**Issue by omkar-hub** [GoogleChrome/web.dev#3214]
**Describe the bug**

Performance audit varies compared to lighthouse tool from webdev tool of chrome browser 

**To Reproduce**
1. Go to 'https://web.dev/measure/'
2. add site  'https://landing.google.com/sre/' for audit
3. Click on Run Audit 
4. It gives ~47 % Performance
Compare with Chrome webdeve tool audit 
1. Open site in Chrome browser 
2. Go to webdev tool 
3. Go to lighthouse
4. Choose performance - desktop
5. Run audit
6. It gives ~99 % performance
 

**Expected behavior**
The Both places 1. web.dev/measure and 2. lighthouse audit from chrome browser should give same result.
![screencapture-web-dev-measure-2020-06-12-11_21_19](https://user-images.githubusercontent.com/12067284/84519104-9c488f80-ac9f-11ea-9315-f036898c8780.png)
[sre-performance.pdf](https://github.com/GoogleChrome/web.dev/files/4771690/sre-performance.pdf)

**Screenshots**

**Comment by robdodson** [comment]
This is possibly occurring because the settings are different. It's a bit hard to see but at the bottom of the page we state that web.dev will run with a simulated mobile device on a 3g connection with 4x CPU slowdown.

Also web.dev will be testing your app from the us-central datacenter, so you may get different results depending on if your app is on a CDN or not.

**Comment by omkar-hub** [comment]
Got it Thank you Rob. This has cleared the things.
