### ISSUE TITLE
Live page is broken because of cached CSS in service worker

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#3243]
**Describe the bug**
Tried deploying #3196 but the service worker is serving cached CSS so the page renders broken if you've previously visited the site:

![Screen Shot 2020-06-16 at 8 50 31 AM](https://user-images.githubusercontent.com/1066253/84798282-9e686200-afaf-11ea-8ed8-35f80bcba364.png)

**Comment by robdodson** [comment]
It seems like our CSS is precached in build.js, then we call `precacheAndRoute(manifest)` in the sw.js.

Per [the docs](https://developers.google.com/web/tools/workbox/modules/workbox-precaching#serving_precached_responses):

> The response strategy used in this route is cache-first: the precached response will be used, unless that cached response is not present (due to some unexpected error), in which case a network response will be used instead.

So we're serving fresh html, but cached CSS.

**Comment by robdodson** [comment]
The docs recommend using versioning strings in your CSS (`app.123jlksdf.css`) so you avoid this issue. We already do this for our js but not our css because we weren't sure what was the best way to pipe that file name back into eleventy so it could generate the pages correctly.

My quick fix for this bug is going to be to tweak the CSS file name in layout.njk (maybe just adding a query string). But we should see if we can switch to adding version numbers to the file name itself so we avoid this issue in the future.

**Comment by jeffposnick** [comment]
https://github.com/GoogleChrome/web.dev/pull/3245 is not a viable long-term fix, as you end up in a situation now where `app.css` is precached, but never used—your web app is going to request `app.css?v=...` and that will never match the precached URL. This means that, among other things, your CSS won't load reliably while offline.

I also want to point out that this is an issue that folks need to think about whenever any type of caching is used, whether it's via a SW or via HTTP Cache-Control headers. If there were no SW involved, for instance, and your served all your HTML with HTTP caching disabled but with HTTP caching enabled on an unversioned `app.css`, you'd have the same problem. The nice thing about having a SW in place is that you have more _options_ for solving that problem.

The best way to solve that problem is to list both the HTML that loads your subresources, and the actual subresources themselves, as part of the same precache manifest. This ensures that you'll have your HTML and subresources in sync. This would work whether or not you add hashes to your subresources.

I don't believe that precaching HTML is the approach that web.dev takes, though, as the HTML is loaded with a stale-while-revalidate strategy and the subresources are all precached. One solution would be to start precaching what would effectively act as the App Shell HTML and use that to handle all or at least most) navigations.

Another approach is to go on using runtime caching—stale-while-revalidate or network-first—for your HTML, and include hashes in all your precached subresource URLs. This increases the chance that there will be a cache miss when loading a page—a stale HTML document from 30 days ago might request `app.1234.css` but only `app.5678.css` exists in the SW cache—but at least you'd know when there's a loading failure in that case. You can work around this failure by either keeping your old versioned URLs live on your server indefinitely, so that the server could respond to both `app.1234.css` and `app.5678.css`, even though only one of those URLs will be in the local SW cache. Alternatively, you could work around this failure by detecting an `error` event when loading your subresources, and using that as a signal to do a force-reload of your page.

I put together a short talk about the topic of how things can go wrong when loading cached subresources at https://pawll.glitch.me/. The focus there is on the React ecosystem, but the ideas are applicable here as well. It also covers some best practices/gotchas when using `skipWaiting()` to accelerate the expiration of your previously precached URLs.

**Comment by jeffposnick** [comment]
Also CC: @philipwalton, as I know he some specific thoughts about patterns in the versioned CSS space, including introducing things using `semver` major revision concepts to indicate when a CSS change will be incompatible with previously cached HTML.

**Comment by robdodson** [comment]
> #3245 is not a viable long-term fix, as you end up in a situation now where app.css is precached, but never used—your web app is going to request app.css?v=... and that will never match the precached URL. This means that, among other things, your CSS won't load reliably while offline.

Yeah I did that as an attempt to quick fix the bug.

> The best way to solve that problem is to list both the HTML that loads your subresources, and the actual subresources themselves, as part of the same precache manifest. This ensures that you'll have your HTML and subresources in sync. This would work whether or not you add hashes to your subresources.

I believe we are using an app shell model now (we load cached .json into a partial template). Is the idea that any time we rev a resource like our CSS that we also rev the shell so it knows to request the right CSS file?

> I put together a short talk about the topic of how things can go wrong when loading cached subresources at https://pawll.glitch.me/. The focus there is on the React ecosystem, but the ideas are applicable here as well. It also covers some best practices/gotchas when using skipWaiting() to accelerate the expiration of your previously precached URLs.

Thanks I'll take a look!

**Comment by jeffposnick** [comment]
Actually, sorry, I misremembered the HTML generation setup that you all are using.

https://github.com/GoogleChrome/web.dev/blob/91875d47f0d7e2ef598daf723b2035077c28d811/src/lib/sw.js#L216-L218

seems to be the relevant bits.

**Comment by jeffposnick** [comment]
Okay, sorry for the noise, I looked through the SW logic and cache setup again and feel more qualified to comment on the actual setup you're using now 😄 

You're using network-first for your HTML (it's not an App Shell model for initial navigations, though subsequent "fake" SPA-style navigations are used), and precaching unversioned CSS/JS URLs that are loaded by that HTML. The root cause of the issue tracked in this bug is that https://github.com/GoogleChrome/web.dev/pull/3196 introduced some changes to both the HTML for https://web.dev/live/ and for `app.css`, and while the new HTML was fetched network-first, `app.css` that didn't match what the HTML needed was used directly from the precache.

The force-reload logic that's currently in place detected the update to the precached `app.css` and the page eventually looked correct following that reload, so perhaps "eventual" consistency is good enough.

Given that precaching all your HTML is not viable, and that switching to a real App Shell model might not be in the cards, getting to the point where you did hash your CSS would at least have avoided this issue. If your https://web.dev/live/ HTML that was loaded network-first contained a reference to `app.5678.css` then the fact that `app.1234.css` was in the precache wouldn't have mattered for that initial navigation; the CSS request would go to the network and get exactly the version that you needed. (And then in the background, `app.1234.css` in the precache would be swapped out for `app.5678.css`.) That would have avoided the "eventually consistent" behavior with an initially consistent loading experience, albeit one that would take slightly longer, as `app.5678.css` would have to be retrieved from the network.

So yeah, that's all to say that I think finding a way to get versioned CSS/JS URLs injected into your HTML would be worthwhile.

**Comment by robdodson** [comment]
Thanks @jeffposnick!
