### ISSUE TITLE
content: Declarative Scroll Linked Animations [2020-09-03]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3325]
* [draft](https://docs.google.com/document/d/1aDa2ba5-7lxupVsjN5-QEGyMRoIbQDneCUoLWvPBkXg)
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/YoX9b0eVLfg)

**Comment by argyleink** [comment]
rad, draft begun

**Comment by argyleink** [comment]
🧟  it's not dead!

**Comment by argyleink** [comment]
Draft is ready for a 1st review, can help guide some of the open questions.

**Comment by argyleink** [comment]
still ready!

**Comment by argyleink** [comment]
still ready!

**Comment by argyleink** [comment]
not stale, still delicious! 🍞

**Comment by argyleink** [comment]
hey @rachelandrew, can we revive this please? i'd love to get it out the door, down to hack on it together and carry it across?

**Comment by rachelandrew** [comment]
@argyleink sure - I don't have access to the draft but let me know how I can help. It would go well with the general scroll efforts based on the scroll survey.

**Comment by argyleink** [comment]
access granted 🧙🏻‍♂️

**Comment by rachelandrew** [comment]
@argyleink I did a first pass of this today. There is still a demo to decide about at the end there, but it looks like this isn't far off.

**Comment by rachelandrew** [comment]
@argyleink what's the status of this one? I don't think it's far off ready.

**Comment by argyleink** [comment]
i'm tentative to publish because there's updated syntax (`scroll-offsets` and `time-range`) in the spec that's simpler, but Chromium doesnt support it yet. I'd like to publish the demo's and article when the syntax is stable, since it's simpler. instead of publishing both syntaxes like most articles and demos do today. i also think it'd be nice to ship the post when the updates hit beta/stable, to help spread the word on the newer, easier pieces. 

but i have been doing extra work on it! it's a place i really enjoy spending creative time, it's such a fun feature. let's continue to riff on it!
