### ISSUE TITLE
Automatic update of updated field might be more trouble than it's worth

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#3368]
**Describe the bug**

When our contributors update their branches, a bunch of unrelated files sometimes get updated:

![image](https://user-images.githubusercontent.com/4713486/85760259-83d86c00-b6c6-11ea-86e7-fa02466a6fe6.png)

The PR says that there's 74 modified files while this PR has actually only touched 5-20.

This just happened to @samdutton and I believe it happened to @rachelandrew also.

This can be risky and burdensome to fix because it seems like it requires rewriting git history. So there's the possibility of contributors losing their draft content if they do it wrong. I've been telling people to just copy their content over into a fresh branch.

**To Reproduce**

I don't really know. Our contributors are using some git workflow that doesn't jive well with the auto-update behavior. Rather than training all of our contributors to use a specific git workflow I think it's easier to just disable the auto-update logic and use other means for ensuring that the `updated` field stays up-to-date.

**Comment by samdutton** [comment]
Yup — that's odd. I'm not aware of having opened those files. (And if I
hadn't made changes, the update date shouldn't have been changed, right?)

**Comment by rachelandrew** [comment]
When it happened to me I was using Tower, and rebased from the Master branch using that. I don't mind following specific steps when using git if needed to avoid the problem.

**Comment by robdodson** [comment]
I _think_ this happens if folks run `git merge master` while they're on a branch.

Tried to explain what I think is going on in these two comments: https://github.com/GoogleChrome/web.dev/pull/2956

We can disable the git hook if it's confusing for folks and find an alternative.

**Comment by jpmedley** [comment]
I don't remember having this problem on WebFu. There must be a way to avoid it. cc: @petele

**Comment by kaycebasques** [comment]
It just happened to @agektmr in #3472 

I don't think we're getting enough value out of these auto-updates to justify training our contributors to use a precise git workflow

**Comment by robdodson** [comment]
I just created this PR https://github.com/GoogleChrome/web.dev/pull/3534 which will disable the feature. I think the alternative will be to lint for it. I did build a linter here (https://github.com/GoogleChrome/web.dev/pull/2758) but it's a total beast and might add more complexity than it's worth. I know @kaycebasques that you were working on a linter Chrome extension. I'm not sure if you would want to try and use that instead?

**Comment by kaycebasques** [comment]
Yeah our Extension should be able to catch it

**Comment by kaycebasques** [comment]
FYI just happened again to Katie in https://github.com/GoogleChrome/web.dev/pull/3515/files

**Comment by robdodson** [comment]
Hey folks, @devnook is experimenting with a GitHub action that will automatically set a date to indicate when files are machine translated (https://github.com/GoogleChrome/web.dev/pull/3671)

If this works, maybe we could do something similar for our blog posts.Since it's only looking at the files in a PR it would hopefully avoid the issues folks were experiencing when they did a git merge. The only thing we'd need to watch out for is if someone accidentally creates a big PR that updates several docs. Perhaps we could add a slash command that let's folks manually run this action, or maybe we'd set it to only run after the post has been reviewer approved (I think github fires an event for when you use the Code Review > Approve feature).
