### ISSUE TITLE
content: image CDNs. Should Thumbor be classified as an image CDN?

### ISSUE THREAD

**Issue by jonarnes** [GoogleChrome/web.dev#3431]
* Use this template to request updates to existing content.
* Delete any fields that aren't relevant to your issue. 
* Update the title of this issue with a brief summary of the work to be done.

### What page(s) need to be updated?
* https://web.dev/image-cdns/
* https://web.dev/install-thumbor/

### Why is this update needed?
It's misleading to talk about Thumbor as an Image CDN. It is really a standalone image processor. You get no CDN features with Thumbor. Only if you use a cloud platform like Google Cloud, AWS, or Azure there might be some CDN features to it. However, then it's not free anymore.

I propose talking about Thumbor as a service or API for processing images, while an Image CDN is a full CDN service online signup and management, and most importantly, automatic, real-time image optimization.

**Comment by khempenius** [comment]
I haven't gotten around to this yet but I understand the concern. There's some upcoming content around CDNs and I'll probably hold off on any changes regarding this until after that is live. Truly doing the "CDN" aspect justice would probably take more than a few sentences, so I'd prefer to be able to link to a more detailed discussion of CDNs in order to keep the /image-cdns content mostly focused on image processing.

**Comment by kaycebasques** [comment]
@khempenius WDYT about this now?
