### ISSUE TITLE
Most failing marks on site directly linked to google

### ISSUE THREAD

**Issue by Captndurty** [GoogleChrome/web.dev#3459]
**Describe the bug**
When page speed insights is ran 80% of failing 
marks are directly related to Google. Google Analytics. ssl.gstatic.com
google fonts
![pagesprrd](https://user-images.githubusercontent.com/18713273/86966914-dfc7d980-c137-11ea-9531-5b458860604c.jpg)
  

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by robdodson** [comment]
Hi @Captndurty 

The values that you see aren't failing marks, they're just explaining what adds up to produce the metrics results.
We don't special case google properties since they are part of a performance profile. This section is showing opportunities for improvement. For instance, you might look into lazy loading these scripts if they're not critical to the first render.

Going to close this issue as this repo isn't actually for tracking PageSpeed Insights bugs, we just handle the bugs for the docs at web.dev.
