### ISSUE TITLE
Most contents under /handbook are 404

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/web.dev#3473]
**Describe the bug**
Clicking on most links in this page https://web.dev/handbook/ returns 404.

**Comment by jpmedley** [comment]
Are you still seeing this? I'm not. I think this problem might have been transitory.

**Comment by agektmr** [comment]
I still do. Try with a different browser.

**Comment by kaycebasques** [comment]
It's because they're getting redirected to the site's top-level directory.

Steps to reproduce:

1. Go to https://web.dev/handbook
2. Click **Quick start guide**

Expected:

Link goes to https://web.dev/handbook/quick-start

Actual:

Link goes to https://web.dev/quick-start

@devnook && @robdodson is this something you want to fix, or should we update all links throughout the Handbook?

**Comment by kaycebasques** [comment]
One possible significant issue is that some of the Handbook content has colliding URLs with our main content. E.g. the Handbook page about redirecting content (`https://web.dev/handbook/redirects`) is colliding with the Lighthouse guide about avoiding redirects (`https://web.dev/redirects`)

**Comment by devnook** [comment]
Hi Kayce,

I believe there is already a PR in flight for this (writing from my phone)

**Comment by robdodson** [comment]
This is fixed now.
