### ISSUE TITLE
Add search results page

### ISSUE THREAD

**Issue by Diklla** [GoogleChrome/web.dev#3491]
**Is your feature request related to a problem? Please describe.**
Not having a search results page for the site makes it a bit harder to navigate and it also limits the amount of results you can get each time not allowing for a wide search.

**Describe the solution you'd like**
Add a search results page after clicking enter on a search phrase.

**Additional context**
Just to note that this will not take anything away from the current experience.

**Comment by Diklla** [comment]
@kaycebasques added as discussed

**Comment by robdodson** [comment]
Sorry for the super slow response.

Thanks for filing this feature request. We're currently working on a new site which will have a more robust search experience and we'll hopefully be able to bring that back to web.dev.

If it's ok, I'm going to close this issue for now because we don't have immediate plans to do any work on the existing web.dev search experience but we'll likely revisit this in 2021
