### ISSUE TITLE
Add http authentication to access secured folders

### ISSUE THREAD

**Issue by ChriStef** [GoogleChrome/web.dev#3668]
Please consider adding a user/password folder authentication, so ex. when no public the dev brunch folder to be able to measure!

**Comment by robdodson** [comment]
I don't think we plan to add this feature because we don't want to get into the practice of storing credentials for folks. It opens us up to a lot of extra security and privacy issues.

I think if you need this feature I'd suggest using Lighthouse directly: https://github.com/GoogleChrome/lighthouse/blob/master/docs/authenticated-pages.md
