### ISSUE TITLE
Improve LCP

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#3810]
LCP is the one vital where we tend to go over budget. I think it's mostly caused by our render blocking CSS (which we should inline) and our reliance on material icon fonts which are render blocking because they can't be swapped.

I'm creating this Epic so we can track the work needed to improve our score.

**Comment by prathamesh-gharat** [comment]
Reference page: https://web.dev/async-clipboard/

Some points to think about.

1. Should the iframe be lazy-loaded? Because they and their resources are currently taking priority over other resources (e.g. fonts).
2. Should the fonts be preloaded?

There are rare scenarios (specific text & widths combinations) where font swapping will cause a layout shift: e.g.: https://youtu.be/XmLz6b1Kbmo

For material icons I would suggest evaluating two options:
1. Remove icons from the font files which are not being used with the goal to reduce the file size. (Lower size = Faster download = Faster rendering)
2. Replace them with SVGs ( Important icons like menu/search can be inlined into HTML ) with the goal of requesting the least resources and faster paints.
