### ISSUE TITLE
A broken Glitch in Route prefetching in Next.js

### ISSUE THREAD

**Issue by mihajlija** [GoogleChrome/web.dev#3818]
**Describe the bug**
In [Prefetching with custom routing](https://web.dev/route-prefetching-in-nextjs/#prefetching-with-custom-routing) section the "nextjs-routing" app is not working.

The app has been "suspended", there's no editing option, I could only download the entire project. 

![web dev_route-prefetching-in-nextjs_](https://user-images.githubusercontent.com/17127567/91976802-d61ab680-ed21-11ea-87d7-ce08e762e02a.png)
![glitch com_edit_](https://user-images.githubusercontent.com/17127567/91976811-d9ae3d80-ed21-11ea-9de0-39dba6013b2a.png)

**How to fix:** The project works locally, I'll create a new Glitch and replace the broken one in the post.

cc @robdodson Another Glitch issue. Is there a mechanism for Glitch to notify us when our apps break? I got a twitter DM from a user about this.

**Comment by robdodson** [comment]
> cc @robdodson Another Glitch issue. Is there a mechanism for Glitch to notify us when our apps break? I got a twitter DM from a user about this.

Not that I know of. In the past we've filed tickets on their support forum to figure out why a glitch was suspended. Sometimes it's because of how we were running webpack (it was slowly filling up the disk). You might see if @housseindjirdeh can take a look at your Glitch to make sure it's not running into that same issue. He's fixed it elsewhere.
