### ISSUE TITLE
Static files served from App Engine have a Last-Modified of 1980

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/web.dev#3913]
If you take a look at any of the static files that are served by `web.dev`, they all have

```
last-modified: Tue, 01 Jan 1980 00:00:01 GMT
```

I believe that the underlying `mtime` values for those files "on disk" in App Engine are set to that 1980 date as well.

This is messing up both `Last-Modified` timestamps as well as weak Etag generation, which relies on a combination of `size` and `mtime` to [generate](https://github.com/jshttp/etag/blob/4664b6e53c85a56521076f9c5004dd9626ae10c8/index.js#L126-L131) a (hopefully, but apparently not) unique value that is then hashed.

It's probably worth following up with some folks who know more about how files get uploaded to App Engine to figure out whether there's some way of preserving the underlying timestamps and not resetting them all to 1980. Without that, I don't think that any form of `Cache-Control` for the `web.dev` static files is safe.

C.f. https://github.com/GoogleChrome/web.dev/pull/3912

**Comment by jeffposnick** [comment]
https://stackoverflow.com/questions/63813692/why-is-the-last-modified-incorrect-on-google-cloud-platform-app-engine tracks the same thing, but I don't see a resolution there other than a suggestion to follow up with the GCP team.

**Comment by jeffposnick** [comment]
https://issuetracker.google.com/issues/168399701 was reported a week ago, so maybe this is a recent regression?

**Comment by robdodson** [comment]
It looks like the `no-store` change I added didn't fully resolve the issue. I'll see if disabling etags entirely helps.

**Comment by robdodson** [comment]
As an example, when I visit https://web.dev/codelab-http-cache/

Here's what I see in the network panel:
![image](https://user-images.githubusercontent.com/1066253/93809917-bc72dd80-fc02-11ea-9f7a-b9b19e158bc4.png)

It kind of looks like the service worker might be returning the html unless I'm reading that wrong. But it's also showing that bootstrap.js is showing a 304. bootstrap.js requests app-*.js, and since bootstrap.js is stale, it's requesting a version of app-*.js that doesn't exist on the server anymore.

**Comment by jeffposnick** [comment]
That second line, with the little gear from it, is the service worker doing a conditional `fetch()` for the HTML, and getting back an HTTP 304 (indicating that nothing changed and the copy in the HTTP cache is fine) from the server. If you `Cache-Control: no-store` changes were in effect, then I wouldn't expect to see an HTTP 304.

If I start from an Incognito window, I don't see an HTTP 304 from the server, even after reloading the same page a couple of times.

That being said, if files uploaded to App Engine are all getting their modified timestamps clobbered, then it doesn't seem like it's safe to serve _anything_ with a weak Etag that depends on the modified timestamp. In that scenario, file size ends up being the only thing that uniquely determines the Etag, and files with the same size but slightly different contents seem common enough.

**Comment by robdodson** [comment]
It looks like the first two lines are showing Cache-Control: no-store so I think my change was running.

I'm curious if I should tell express static to disable both etag and last-modified? I'm not enough of a caching expert to know how the browser cache would check if a resource can be reused at that point (but maybe we just rely on the service worker to handle it all?)

**Comment by jeffposnick** [comment]
I believe the no-store returned from the server only affects the **next** request, though. When you reload the page do you still see a 304 response?

**Comment by robdodson** [comment]
unfortunately i did a hard refresh at one point and now that seems to have cleared my cache so i'm not able to reproduce the error anymore

**Comment by samthor** [comment]
So Rob's fix updates the HTML to be no-store but I want to call out how our
JS loads. I am honestly a bit confused.

Our HTML fetches `/bootstrap.js?<hash>`. This is more permissive than
including the hash in the JS filename itself, because if the HTML is wrong,
we still get bootstrap JS. That file then inserts a script tag which
includes "app-abcdef.js".

- If you're actually hitting the exact cache for "/bootstrap.js?<hash>",
it's incredibly likely you've also cached the related app files (since
you cached it as part of loading, or as part of the SW).
- If you're not, then the live/up-to-date bootstrap.js file will just point
to new files, which.. should also be fetchable since you just got the new
bootstrap.

**Comment by robdodson** [comment]
Hoping to fix some of this with the move to Firebase Hosting in #4381. At least the Last Modified header should start showing the correct date/time 😅
