### ISSUE TITLE
Add notice banner to web share and web share target articles

### ISSUE THREAD

**Issue by TimvdLippe** [GoogleChrome/web.dev#3933]
**Describe the bug**
There are two APIs that are similarly named: https://web.dev/web-share/ and https://web.dev/web-share-target/ To reduce confusion, could either article add an notice/warning banner at the top of the article to explain the difference between the two? My friend got confused when searching for the target api, while only discovering the first article.

**To Reproduce**
1. Want to read more about web share target
2. Google for "web share"
3. Find https://web.dev/web-share/
4. Be confused, as that is not the target api you are looking for

**Expected behavior**
A clear description of the differences between the two APIs, preferably in a notice banner at the top of the articles.

**Screenshots**
n/a

**Comment by robdodson** [comment]
@jpmedley what do you think about updating these posts?

**Comment by jpmedley** [comment]
I'm on it.

**Comment by jpmedley** [comment]
Now I'm a little confused. Both articles already have that notice. That's not to mention that the titles point to the difference: "Sharing like a native app..." and "Receiving shared data..." Could you ask your friend if there was a specific line that confused him?

![image](https://user-images.githubusercontent.com/8204171/94202119-eaaa2480-fe71-11ea-95ad-961b6f7bc727.png)

![image](https://user-images.githubusercontent.com/8204171/94202135-f990d700-fe71-11ea-979c-830d006c036d.png)

**Comment by TimvdLippe** [comment]
Right, I completely missed these notice banners, just as my friend did. Can we change the coloring to make them more apparent? E.g. something like a yellow warning. That should hopefully let it stand out more.

With the blue coloring, my initial reaction is "this is additional information that provides more depth". As such, it wouldn't be the place I am looking for links to the other article.

**Comment by kaycebasques** [comment]
Thanks for the feedback, @TimvdLippe.

This sounds like an instance of [banner blindness](https://www.nngroup.com/articles/banner-blindness-old-and-new-findings/).

I don't think we'll be able to reach an objective agreement about what color of banner is optimal.

We might however argue whether or not this should be in an aside. If we consider the text in relation to the dictionary definition of "aside":

> a remark that is not directly related to the main topic of discussion.

On one hand you might argue that it's appropriate to put this in an aside because we're talking about a different but related API. On the other hand, if the two APIs are deeply intertwined, i.e. it's unlikely you'll use one API without using the other, then perhaps this information shouldn't be in an aside at all. Perhaps it should just be a normal paragraph. That would avoid the banner blindness risk.

It'll be a bigger effort/discussion to determine how prevalent banner blindness is among our users.

@jpmedley I'll leave it up to you to decide what to do here.
