### ISSUE TITLE
content: trusted types [Publish Date: Mar 25]

### ISSUE THREAD

**Issue by franktopel** [GoogleChrome/web.dev#4139]
As it currently stands, any complex codebase wishing to adopt trusted types and require these using the CSP directive `require-trusted-types-for 'script'` is likely to run into this 

    "This document requires 'TrustedScriptURL' assignment."

blocker. **There is not a single page on the web that explains in an understandable way how to tackle this.**

The best I was able to come up with (and having checked all the links from the only answer - NO, it does not help) is https://stackoverflow.com/questions/62081028/this-document-requires-trustedscripturl-assignment

### What page(s) need to be updated?

https://web.dev/trusted-types/

### Why is this update needed?

No non-trivial codebase can adopt trusted types without an easy-to-understand page that explains **all** the necessary steps (currently https://web.dev/trusted-types/ only features an example creating TrustedHTML via DOMPurify Library), including how to declare **default** handlers for creating TrustedScriptURL objects.

For example our code base has a part where a worker is created using 

```
const workerpath = './js/worker/performance-report.worker.js';
const SEND_WORKER = new Worker(workerpath);
```

Before, we used to create this worker using a `:blob`, but to be able to remove that from the CSP directive `worker-src` we explicitly converted that to an external script, found a way to integrate that into our build process, only to find ourselves punished for this when we are trying to make the switch to trusted types next.

### What's the deadline?

Considering this feature (trusted types) has been promoted in March already, I really think it's about time for a complete documentation. And **please**, fwiw, **don't link me any spec documents**. That kind of documents is **unreadable** for an average web developer.

#### Is it a hard deadline?

If you want to promote a safer web platform - and this is core interest to Google - make sure you enable people to use the features you're promoting!

**Comment by kaycebasques** [comment]
Thanks for the detailed feedback, @franktopel.

@koto  PTAL

**Comment by koto** [comment]
Thanks again for the feedback, and sorry that the article did not meet your expectations. To quickly address the issue you raised, in order to create `TrustedScriptURL` objects, you need something that looks roughly like:

```javascript
const myUrlPolicy = trustedTypes.createPolicy('name', {
  createScriptURL: (s) => {
    // Make sure that the URL is what you expect here
    return s;
  }
});

new Worker(myUrlPolicy.createScriptURL(url));
```

Essentially, for risky functions, where you previously passed a string, now you need a matching type. For `Worker` constructor it's `TrustedScriptURL` (this is formally defined [here](https://w3c.github.io/webappsec-trusted-types/dist/spec/#html-workers)). You can get that type from any policy object's `createScriptURL` function.

**Comment by franktopel** [comment]
Thanks for the quick answer. How would I achieve the same using a `trustedTypes.createPolicy('default' , { createScriptURL: (s) => { /* ???? */ })`. Or is that only available for TrustedHTML? I've tried that and Chrome still complains `"This document requires 'TrustedScriptURL' assignment."`.

**Comment by koto** [comment]
> Thanks for the quick answer. How would I achieve the same using a `trustedTypes.createPolicy('default' , { createScriptURL: (s) => { /* ???? */ })`. Or is that only available for TrustedHTML? I've tried that and Chrome still complains `"This document requires 'TrustedScriptURL' assignment."`.

It should work, there's nothing special about `TrustedHTML`:

`data:text/html,<meta http-equiv=content-security-policy content="require-trusted-types-for 'script'"><script>trustedTypes.createPolicy('default', {createScriptURL: s=>s});new Worker('data:,console.log(1)');</script>`

> I like the `default` policy thing alot over the named policies (DOMPurify obviously making this very easy), because it doesn't enforce actually changing code. Is there a library that supports sanitizing URLs which could be suitable and configurable enough for the purpose?

Unlike HTML, you don't actually sanitize script URLs - usually you need to check if they meet your criteria (i.e. that they are part of your application). These rules are necessarily application-specific, so a library would not be terribly useful, since the real problem is how to configure it (e.g. Do you have one origin of script URLs to allow? A few origins? a URL prefix? Perhaps only a few hardcoded URLs? Do you want to log things as they pass through the policy?, etc.). See [example 2 in the spec](https://w3c.github.io/webappsec-trusted-types/dist/spec/#policies-hdr) that shows a code like this.

**Comment by franktopel** [comment]
For testing purposes, I have the following being the first lines of code in my `entry.js`:

```javascript
import DOMPurify from 'dompurify';

if (window.trustedTypes && window.trustedTypes.createPolicy) { // Feature testing
    window.trustedTypes.createPolicy('default', {
        createHTML: (string) => DOMPurify.sanitize(string, {RETURN_TRUSTED_TYPE: true}),
        createScriptURL: string => string,
    });
}
```

Since we need to analyze what needs to be done in our framework context to make URLs safer, for the time being I'm just passing it through as it is, to get things running again.

Unfortunately, I'm still getting

![image](https://user-images.githubusercontent.com/10668603/97541932-3d718180-19c6-11eb-9d6d-9edc82d88ad2.png)

**Comment by koto** [comment]
Since the callstack points to `__webpack_require__`, I assume that the call executes before the default policy was created (alternatively, the call is made in a different window/frame/worker than the one that created the default policy; policies are per-document). 

The default policy, if you choose to use it instead of the other policies, needs to be created before the XSS sinks are called. Usually, if you're in control of the code using the sinks, it's more appropriate to actually rewrite them, and leave the default policy for the 3rd party code using the sinks, that you cannot change yourself.

**Comment by franktopel** [comment]
`entry.js` is my entry point for webpack bundling, and the importing of DOMPurify and subsequent definition of the default policy are the very first lines in that file. Nothing precedes those. I am not assuming webpack changing the order of code when bundling.

**Comment by koto** [comment]
The policy creation is synchronous - check the URL I posted above, the call touching the sink is using the default policy created in a previous statement. I'm not in a position to debug your application, but perhaps there are multiple scripts loaded in your application simultaneously, and one of them executes before the one containing `entry.js`. 

The TT API is pretty straightforward - after creating a default policy in a document (or a worker) (which is synchronous), it's used implicitly for the lifetime of the document. If you notice this is not the case and have a reproduction case, [file a Chromium bug](https://crbug.com).

**Comment by franktopel** [comment]
Even if I put

```javascript
if (window.trustedTypes && window.trustedTypes.createPolicy) { // Feature testing
    window.trustedTypes.createPolicy('default', {
        createScriptURL: string => string,
    });
}
```
right **before** the offending lines of code, where the worker is created, in `bm-performance-report-manager.js`, I'm still getting the above error.

>perhaps there are multiple scripts loaded in your application simultaneously

No, the bundle created by webpack 4.26.1 is the **only** script file on the test page.

**Comment by franktopel** [comment]
> Since the callstack points to __webpack_require__, I assume that the call executes before the default policy was created

Okay, I will try and debug that. How can I check if a policy has already been registered?

**Comment by koto** [comment]
Re: multiple policy - if you're not using `trusted-types` directive in the CSP, but only `require-trusted-types-for`, then you can create a default policy multiple times, but the first one will be used:

```
data:text/html,<meta http-equiv=content-security-policy content="require-trusted-types-for 'script'"><script>trustedTypes.createPolicy('default', {createScriptURL: s=>s + ';console.log(1)'});trustedTypes.createPolicy('default', {createScriptURL: s=>s + ';console.log(2)'});new Worker('data:,');</script>
```

If you use `trusted-types` directive, some policy creation may be forbidden (but this would be visible, the code would throw).

> How can I check if a policy has already been registered?

Nothing in the API, sadly - this is tracked in https://github.com/w3c/webappsec-trusted-types/issues/270. You can add statements surrounding `createPolicy` call, e.g. logging issues. 

In any case, please file a bug in Chrome if you get to a minimal test case. It's possible we made a mistake of course, we're not using the default policy too much ourselves.

**Comment by franktopel** [comment]
`<meta http-equiv=content-security-policy` does that attribute value not need quoting?

**Comment by franktopel** [comment]
> then you can create a default policy multiple times, but the first one will be used

If I have one part of the code 

```javascript
window.trustedTypes.createPolicy('default', {
    createHTML: (string) => DOMPurify.sanitize(string, {RETURN_TRUSTED_TYPE: true}),
});
```

and later, a part that does

```javascript
window.trustedTypes.createPolicy('default', {
    createScriptURL: string => string,
});
```
does your statement mean that the second call to `createPolicy` never comes to fruition?

**Comment by koto** [comment]
Yes, we found the root cause then :) The policy is not changed after its creation, and the missing `create*` functions cause the rejection of the values. We decided against merging, as that would be a surprising behavior, and an antipattern - e.g. you might be able to alter a policy that another library already created. 

You need to add all `create*` functions in a single `createPolicy` call. The case is worth spelling out, I'll make a note to describe that in a documentation.

**Comment by franktopel** [comment]
Okay, your suggestion to do "manual" debugging using the good old console.log helped here. Webpack does in fact change the execution order. By the looks of it it automatically pulls all the imports in a file to the top.

Thanks alot for your help.

**Comment by franktopel** [comment]
For future readers:

If you are using webpack and need to make sure your trusted types policy registration is executed before any of your other code that is imported in your entry point, you need to put the policy registration code in a separate JS file and `import` that in your entry point first.
