### ISSUE TITLE
content: flexbox (learn css) [2021-05-01]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#4170]
* [draft](https://docs.google.com/document/d/1gO-cv6PdC5v8eH8zJak4kAPyBc_WyCxNKBkoCRuzPpk/edit)
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/dLLhYyyNWRU)

**Comment by rachelandrew** [comment]
@kaycebasques I don't think I can access the email thread on webdev-content so I'll post to this issue.

I have made examples for the flexbox guide today, they are linked in the document where I think they would go. Also as a group here: https://glitch.com/@rachelandrew/learn-flexbox

As per the discussion I've used the web.dev colors/fonts/border-radius. So the main color being the blue, and the pink as a highlight when I'm doing something specific with one item to help people see which one is changing. Tried to keep these as simple as possible. I'm trying essentially to demonstrate just one thing at a time.

Happy to bikeshed these if anyone has opinions on one or all of them.

There are a few diagrams needed, I have a feeling it was mentioned somewhere about getting someone with drawing skills to make those. I can come up with something but they might be a bit designed by programmer. If someone else will do these I can do a rough sketch of each though of the bits I think need showing if that is helpful.

cc: @robdodson @una

**Comment by robdodson** [comment]
I think these are looking great. One suggestion might be to consider alternating the blue color a bit so maybe every even child would be a shade lighter? If I recall, I think you did this in some of your css grid videos?
![image](https://user-images.githubusercontent.com/1066253/99309065-bb7ab880-280d-11eb-839d-2821adad914d.png)

**Comment by una** [comment]
These look great! 

I agree with the shade variance. The current colors are very vivid, and I feel like we could make them a bit easier to read. I like adding borders for vivid color, and a lighter background-color within the element body.

A few other small bikesheddy bits:
- We (Adam and I) tend to prefer setting typefaces to `system-ui` because it adds a little bit of polish that feels like it goes a long way.
- Can we add a gap to demos like [this](https://glitch.com/~flexbox-guide-align-self) and [this](https://glitch.com/~flexbox-guide-order) to make it a bit more readable? Or increase the rounded corner size? Or change the colors so they are all different? Or the border style? Just a few suggestions.
- It might be more clear in [this](https://glitch.com/~flexbox-guide-order) demo if the example text for `item 2` said `order: 2` on the item itself
- Perhaps show what [this](https://glitch.com/~flex-guide-flex-wrap) looks like without wrap? A toggle option?

**Comment by rachelandrew** [comment]
@una I used the font and colors suggested in email (using the web.dev palette) but we can change them.

I didn't want to add a gap to the flex demos because of the lack of support in Safari, thinking that they would then look the same for everyone, but maybe you aren't worried about that.

**Comment by robdodson** [comment]
> @una I used the font and colors suggested in email (using the web.dev palette) but we can change them.

oh sorry I should have mentioned that a while back we switched to system-ui for the body type on web.dev so I think we're OK to use it in the demos as well

**Comment by rachelandrew** [comment]
@una @robdodson I've made a bunch of updates based on the above so take a look when you get chance.

**Comment by robdodson** [comment]
I think these are looking great! The only thing I was wondering is if it would be possible to make the lighter blue background just a tiny bit darker. It's at a 4.3 contrast ratio with the white text (https://contrast-ratio.com/#%235F67FF-on-white) so maybe just a few steps darker will get it to 4.5?

**Comment by rachelandrew** [comment]
@robdodson done!

I have also a set of examples for the Grid Guide (don't think there is an issue for it) https://glitch.com/@rachelandrew/learn-grid / https://docs.google.com/document/d/1SJjf0TJmF000mkuTPCvi_YdMVlBH351iyoEmY15TfU8/edit?usp=sharing 

I'm actually at the end of the contract today where I was working on these pieces, though I'm now on another contract for Google documenting MDN APIs so if there is something needs tweaking on these just let me know.

**Comment by robdodson** [comment]
These look great (and I like the Glitch logo you made! :))

I think once we get the new developer.chrome.com shipped next week Kayce and I can circle back and see about getting all of this live on the site. Thank you for working on it!

**Comment by kaycebasques** [comment]
I can close these because we're tracking the work elsewhere now.
