### ISSUE TITLE
content: Chromium compat goals 2021 [2021-02-05]

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/web.dev#4490]
* [thread](https://groups.google.com/a/google.com/g/webdev-content/c/0eRCFezzCC8)
* draft: TBD

**Comment by robnyman** [comment]
Ok, our draft is ready for review!

[Eliminating 5 compat pain points in 2021](https://docs.google.com/document/d/1scV0Xx_mb0T1TSCOJKjXops2o5-e0rHNPuGHJqOavA4/).

The goal is to publish this on Mar 22nd, and needs to be a fixed date, since there will be synced announcements from Microsoft and more at the same time.
