### ISSUE TITLE
Same-Site vs Cross-Site Explanation

### ISSUE THREAD

**Issue by PicksUpTheGauntlet** [GoogleChrome/web.dev#4647]
**Describe the bug**
The definition of eTLD+1 seems to either contradict the proceeding examples or a statement is incorrect.

The reader is provided with a representation of what an eTLD+1 is:

> The whole site name is known as the eTLD+1. For example, given a URL of https://my-project.github.io , the eTLD is .github.io and the eTLD+1 is my-project.github.io, which is considered a "site". In other words, the eTLD+1 is the effective TLD and the part of the domain just before it.

Following the above, a definition of same-site and cross-site is provided to the reader:

> Websites that have the same eTLD+1 are considered "same-site". Websites that have a different eTLD+1 are "cross-site".

Yet, in the list of examples (screenshot provided,) there's mention that a different subdomain for a site _is_ **same-site** because subdomains don't matter. The subdomain is the `+1`, so that would infer (based on the definition above) that the example of **login.example.com** is in-fact, cross-site.

**To Reproduce**
https://github.com/GoogleChrome/web.dev/blob/main/src/site/content/en/secure/same-site-same-origin/index.md 

**Expected behavior**
Perhaps, I'm misunderstanding this... I _believe_ that the definition of same-site and cross-site should be corrected by removing the `+1` from `eTLD+1`:

i.e., `Websites that have the same eTLD are considered "same-site". Websites that have a different eTLD are "cross-site".`

I'm happy to open a PR if this is valid.

**Screenshots**
<img width="848" alt="image" src="https://user-images.githubusercontent.com/8835020/107561316-6223ea80-6bac-11eb-9365-567cb418a219.png">

**Comment by miketaylr** [comment]
I agree this stuff is pretty confusing! But it's useful to look at the image provided in the article:

![same-site](https://user-images.githubusercontent.com/67283/107805597-2d8a6d00-6d2b-11eb-9418-de46d089f0c8.png)

The eTLD in this image is just ".com". But for a site on github.io, the eTLD is "github.io" (because it appears on the Public Suffix list, see https://publicsuffix.org/list/public_suffix_list.dat & https://en.wikipedia.org/wiki/Public_Suffix_List). While the "foo" in "foo.github.io" *looks* like a subdomain, browsers don't treat it that way for security and privacy reasons.

> Perhaps, I'm misunderstanding this... I believe that the definition of same-site and cross-site should be corrected by removing the +1 from eTLD+1:

If browsers did that, it would imply that all "dot com" sites are same-site with each other, which would be bad. :)

**Comment by PicksUpTheGauntlet** [comment]
I see! I guess I should reading a bit more carefully 😅 Thanks for taking the time to explain.

**Comment by miketaylr** [comment]
All good! This is a very confusing concept -- thanks for filing an issue!
