### ISSUE TITLE
Code highlighting not working within nested components 

### ISSUE THREAD

**Issue by mihajlija** [GoogleChrome/web.dev#4884]
Code highlighting doesn't work when used in a `{% Compare %}` within `{% Details %}`. Related to #4862.

cc @robdodson @MichaelSolati @devnook 

**Example**
https://deploy-preview-4862--web-dev-staging.netlify.app/strict-csp/#step-2:-set-a-strict-csp-and-prepare-your-scripts

**Screenshots**
![image](https://user-images.githubusercontent.com/17127567/110938390-16439d00-8334-11eb-8c4d-ae0518116512.png)

**Comment by robdodson** [comment]
@mihajlija it seems to be rendering ok for me locally and on netlify. Maybe the author changed something?

![image](https://user-images.githubusercontent.com/1066253/110968572-8dfdd180-830c-11eb-8d00-6d5e78346fa2.png)

The Details example isn't using highlighting because the language is set to `text` which I think is the correct syntax for Headers

![image](https://user-images.githubusercontent.com/1066253/110968797-cc938c00-830c-11eb-9ff4-1d9f3d75e3a5.png)

**Comment by lweichselbaum** [comment]
Thanks for taking a look @robdodson.
Only the (javascript) snippets *inside* the details sections are affected.

E.g.
https://deploy-preview-4862--web-dev-staging.netlify.app/strict-csp/#add-a-nonce-attribute-to-lessscriptgreater-elements

![image](https://user-images.githubusercontent.com/13779502/110969799-641ecc00-8359-11eb-823a-35bd597d04aa.png)

**Comment by robdodson** [comment]
oh I see. Yes this was recently fixed (yesterday in fact!) If you pull from main and rebase your branch it should work:

![image](https://user-images.githubusercontent.com/1066253/110973957-cbfdf400-8312-11eb-8abd-e496959e0ec8.png)

No worries if you're not comfortable rebasing the branch, I think the highlighting will work regardless.

**Comment by mihajlija** [comment]
Noted, thank you! @robdodson

**Comment by lweichselbaum** [comment]
Great timing! Thank you @robdodson!
