### ISSUE TITLE
Content : <video> both a current & future consideration for LCP 

### ISSUE THREAD

**Issue by ecarlisle** [GoogleChrome/web.dev#4907]
**Describe the bug**
`<video>` is stated to be both a current and future consideration for LCP.

**To Reproduce**
1. Go to https://web.dev/lcp/#what-elements-are-considered
2. `<video>` is listed under _"the types of elements considered for Largest Contentful Paint are:"_
3. Just below reads: _"Additional elements (e.g. `<svg>`, `<video>`) may be added in the future as more research is conducted."_

**Expected behavior**
`<video>` should appear as either a current or future consideration. It appears to be listed for both.

**Suggestion**
The qualification _"(the poster image is used)"_ is made. If so, perhaps instead the line item should read as:

- _The `poster=""` image of a `<video>` element._

**Comment by rachelandrew** [comment]
@malchata do you have any thoughts on this issue?

**Comment by malchata** [comment]
`<video>` should be removed from the "future considerations" list, IMO, if it already has an impact on LCP. Also (and @philipwalton, chime in if I'm wrong) I think LCP occurs for `<video>` elements regardless of whether they have a `poster` image in `autoplay` scenarios, but there may be some practical considerations around `autoplay` restrictions.

**Comment by philipwalton** [comment]
`<video>` elements without a poster image are currently not considered. Adding support for `<video>` element (regardless of poster image use) is actively being worked on, but it is not part of LCP today.

As @malchata alludes to, animated gifs are currently considered but an identical autoplay video is not considered (if it doesn't have a poster image), and since the UX is the same in both cases, we want to update the LCP spec and implementation to assess these two cases similarly.
