### ISSUE TITLE
RSS feed by tag

### ISSUE THREAD

**Issue by devnook** [GoogleChrome/web.dev#5036]
“Would it be possible to add a RSS feed by tag ? I’d love to subscribe via RSS to "What’s new in devtools" only.”

**Comment by robdodson** [comment]
Because this mentions devtools, I think we should open a separate ticket for this on developer.chrome.com.

On web.dev we currently support RSS feeds for all tags and authors:

- https://web.dev/tags/web-vitals/feed.xml
- https://web.dev/authors/addyosmani/feed.xml

On author pages it's easy to discover because there's an orange RSS icon:
![image](https://user-images.githubusercontent.com/1066253/113896480-d16a2500-977e-11eb-8a1b-0c9e8a6da991.png)

We should probably add a similar icon to the tag pages:
![image](https://user-images.githubusercontent.com/1066253/113896598-f199e400-977e-11eb-89ce-fe13e98183ea.png)
