### ISSUE TITLE
Error: 5 NOT_FOUND

### ISSUE THREAD

**Issue by mikwehttam** [GoogleChrome/web.dev#510]
Hi, I'm getting this error and can't audit my site, is there anything I need to do? Thanks

Error: 5 NOT_FOUND: No document to update: projects/webdotdevsite/databases/(default)/documents/meta/http:___mysite.com

**Comment by stha** [comment]
Same here 👍

**Comment by sdivakarrajesh** [comment]
I'm not sure if it would work here, but I too tried it for my github page 

> https://sdivakarrajesh.github.io/ 

and got the same error
`Error: 5 NOT_FOUND: No document to update: projects/webdotdevsite/databases/(default)/documents/meta/https:____sdivakarrajesh.github.io__`

**Comment by robdodson** [comment]
Hey folks, thanks for reporting this. We'll look into it ASAP

**Comment by vishnuhariam** [comment]
Same here. I noticed the issue persists for some sites only. I believe this error persists only on slow sites. I have been receiving the Error 5 and Network error interchangeably.

**Comment by SYWSoluciones** [comment]
Same Error. 

Error: 5 NOT_FOUND: No hay documento para actualizar: projects / webdotdevsite / database / (predeterminado) / documents / meta / http: ____ seguroparaviaje.com

**Comment by ebidel** [comment]
Hey all. In an effort to clean up the backed after launch, we recently removed a bunch of URLs from the system that looked like they were invalid (e.g timing out, 403/404/500ing). In some cases there may have been false positives and valid URLs were removed that we could not fetch and reverify (SSL cert is misconfigured but served 200, but otherwise the url was valid).

If this sounds like what you're experiencing, try hitting the "run audit" button again on the measure page while signed in. That should add your url back to the system.

Sorry for the inconvenience.

**Comment by vishnuhariam** [comment]
@ebidel I have tried running the audit multiple times, but I get the same error. Could this be due to usage of free SSLs like LetsEncrypt? Anyways, I was logged in all the time while running the audits. Nothing seems to work for me though.

**Comment by nwmcinc** [comment]
I get this to when I try https://northwestmediacollective.com and I was also thinking its Let's Encrypt maybe something on the ssl?

**Comment by ebidel** [comment]
Investigating. Should be a quick fix.

**Comment by ebidel** [comment]
Can ya'll give it a try now. Should be fixed.

**Comment by ebidel** [comment]
Going to close. Please reopen if you're still seeing issues.
