### ISSUE TITLE
CTA for opening side nav in Courses at top of modules

### ISSUE THREAD

**Issue by una** [GoogleChrome/web.dev#5323]
Learn CSS modules can be like `001 / 023` as a button that opens the side nav

**Comment by robdodson** [comment]
It's been a while since we discussed this so my memory is a bit fuzzy. @una is the idea ath the `000` that appears at the top of the course heading would be clickable, and clicking it would trigger the side navigation to open?

![image](https://user-images.githubusercontent.com/1066253/120719512-42784100-c47f-11eb-90c3-87bfa0af8db4.png)
