### ISSUE TITLE
Discovery: Explore a pattern library solution

### ISSUE THREAD

**Issue by andy-piccalilli** [GoogleChrome/web.dev#5387]
This will extremely depend on how we’re going to tackle [the refactor](https://github.com/GoogleChrome/web.dev/projects/26) as a whole, but grouping and documenting patterns, typography and design tokens will only be useful.

It’ll be useful to document how CSS should be written as part of this too, IMO. 

I’ve done a lot with [Fractal](https://fractal.build/) in the past, but not with Nunjucks, so an early task would be to prototype how that works out. I'd totally be open to something baked into the existing 11ty codebase too cc/ @robdodson

**Comment by robdodson** [comment]
I looked at Fractal in the past as well and was curious if we could use it. It looks like folks have gotten the two to work together, but [it seems like it may have taken some hackery](https://www.allaboutken.com/posts/20191112-extendeing-fractal-components-eleventy-static-sites.html).

I think some of the hackery that they introduced was to enable automatic rebuilding and I'm curious if we could DIY that using chokidar? We already use chokidar for [our eleventy watch task](https://github.com/GoogleChrome/web.dev/blob/main/package.json#L46) because in [our dev task](https://github.com/GoogleChrome/web.dev/blob/main/package.json#L20) we want eleventy to run once to completion and _then_ start watching. But `eleventy --watch` will always cause eleventy to do an initial build so it was building twice.

**Comment by andy-piccalilli** [comment]
Here's another option. I prototyped some Fractal-esque patterns capability with Eleventy at the back-end of last year and it worked out really well. The only issue was that I was running short on time, so opted to use Fractal for ease. 

I _could_ dig it out and get it in a public repo for us to look at? 

The benefit of that is we could integrate it into this repo and use the existing `_includes` etc.

**Comment by robdodson** [comment]
yeah let's give it a look!

**Comment by andy-piccalilli** [comment]
Sweet, I created #5408 for it 👍
