### ISSUE TITLE
Consider Eliminating Manual CDN Upload of Images

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/web.dev#5402]
The explanation I was given was that storing images in the repo made the repo take too long to download during clone. However:

* This occurs only once per computer.
* I can do other things while I'm waiting for a clone to finish.

Contrast this with the current situation where I must take time away from other things to upload images every time I need to use one in an article.

In other words, auto uploading has a neutral effect on my workload, while the current practice has a negative effect on my workload.

**Comment by robdodson** [comment]
I think creating a system to auto-upload images from the repo would be a huge engineering undertaking and I don't think this is something we have the bandwidth to do. To switch back to a model where folks commit their images to the repo we'd need to build a way to manage those uploads, for example: do we re-upload all of the site images on deploy? how do we track which images have already been uploaded? how do we track when someone uploads a revision of an image with the same name? etc.

To make the image uploading faster @MichaelSolati has created a tool https://github.com/MichaelSolati/wdr-beam which should allow you to write your article as you normally would locally and then run a command to push all of the images at once.

**Comment by robdodson** [comment]
> All I was asking for was a return of the ability to just put images in a folder. I've gotten this for free for 25 years. Why does it now take a huge engineering undertaking?

It's true that plenty of sites previously did not do this—but those sites were also shipping unoptimized images and we're trying to correct for that.

We moved to using an image CDN in order to bring the site into compliance with CWV, in particular we had very bad CLS because our images did not have predefined dimensions. Similarly we were loading images which were much larger than they needed to be for the user's screen size because we were not using srcset.

In order to fix both of these issues we moved to a CDN that:
- Gives us predefined image width/heights in the shortcode provided
- Generates images at all dimensions so we can use srcset

You can see the positive effects of this move in our search console data:

![image](https://user-images.githubusercontent.com/1066253/119390328-bb0e1f00-bc81-11eb-9696-63f1800e871a.png)

If you use the command line tool provided by Michael then you should be able to write your posts as you did before—with local images in the post directory—and then you'd run the tool before doing your PR and it will upload all of the images for you and update the markup.

I think a thing worth considering is if we could somehow turn this into a GitHub Action that would run the tool for you and commit the changes back to your PR. If something like that existed would you find it helpful?
