### ISSUE TITLE
Position sticky and scroll-padding-top cause page to scroll up when keyboard focus moves into the app-bar

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#5413]
Boooo. Scrolling the page and then moving focus into the app-bar on the courses section causes the page to scroll up. This is because of a browser bug with scroll-padding-top and position: sticky.

https://user-images.githubusercontent.com/1066253/119051399-f655d880-b977-11eb-97a9-87218fad027f.mp4

This codepen explains the issue: https://codepen.io/robdodson/pen/MWpKOOK

**Comment by simevidas** [comment]
I wanted to test if this issue can be worked around by using `scroll-margin` instead of `scroll-padding`. I’ve modified your demo:

https://codepen.io/simevidas/pen/ZEyxawv?editors=0100

Notice the “Jump” link in the header. This is to confirm that scroll targets correctly appear *below* the sticky header and are not concealed by it.

I have removed this rule

```css
html {
  scroll-padding-top: 64px;
}
```

and added this rule

```css
[id] {
  scroll-margin-top: 64px;
}
```

Of course, using `scroll-margin` is more complicated because you have to apply it to every potential scroll target, but if the page knows in advance which elements will be scrolled to, it’s doable.

Unfortunately, it seems that the issue is still present
