### ISSUE TITLE
content: Change Trusted Types example on the security-headers page

### ISSUE THREAD

**Issue by philippederyck** [GoogleChrome/web.dev#5448]
* Use this template to request updates to existing content.
* Delete any fields that aren't relevant to your issue. 
* Update the title of this issue with a brief summary of the work to be done.

### What page(s) need to be updated?

https://web.dev/security-headers/

### Why is this update needed?

Relevance for developers

### The update

The TT example policy shows how to apply escaping for HTML content:

```
createHTML: str => {
      return str.replace(/\</g, '&lt;').replace(/>/g, '&gt;');
}
```

While this example works, I'm not sure if this is what anyone actually expects when using `innerHTML`. If so, they should use `innerText` anyway. An example with sanitization would be much more useful and applicable in the real world.

**Comment by samthor** [comment]
Commenting because the bot popped this up in my inbox. I don't think your issue is valid.

If you set literally "&amp;lt;" or "&amp;gt;" as an element;'s `.textContent`, it will appear literally as those characters, not as < or >. So you need to use `.innerHTML` to make this work. Of course, because we do that, you need to escape so you don't accidentally create a literal `<script>` tag.

(In general we discourage `.innerText`, it's a weird IE legacy.)
