### ISSUE TITLE
Staging server: support md in html

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/web.dev#547]
prod supports md in html:

```
<div class="aside note">
You can also set [different thresholds for different files](https://github.com/siddharthkp/bundlesize#1-add-the-path-and-maxsize-in-your-packagejson). This is especially useful if you are [code-splitting](https://web.dev/fast/reduce-javascript-payloads-with-code-splitting) a bundle in your application.
</div>
```

We should support that too in the staging server.

**Comment by robdodson** [comment]
To clarify, prod doesn't support this either. We run our own markdown parser during the build step and it ignores any markdown inside of an html block.

I think a better approach would be to mimic what /web's parser does. I think it recognizes keywords like "note:" and turns that, and all the contained content, into HTML.

**Comment by robdodson** [comment]
Also tagging this as a possible thing for @TimvdLippe to look at if he has spare cycles.

**Comment by TimvdLippe** [comment]
I am a bit confused as to what the requested feature is. Are we supporting something that prod does not? Or vice-versa? Or a bit of both?

**Comment by robdodson** [comment]
/web has a feature where you can write markdown like this:

```
note: This is a note!
```

and because they ship markdown to DevSite, DevSite's parser will turn that into:

```
<aside class="note">This is a note!</aside>
```

But for web.dev we don't ship markdown to DevSite—we ship HTML. If you want a note, you have to write `<aside class="note">` yourself. But a lot of folks do that and then put markdown inside of the aside.

```
<div class="aside note">
You can also set [different thresholds for different files](https://github.com/siddharthkp/bundlesize#1-add-the-path-and-maxsize-in-your-packagejson). This is especially useful if you are [code-splitting](https://web.dev/fast/reduce-javascript-payloads-with-code-splitting) a bundle in your application.
</div>
```

Our markdown parser won't parse that inner markdown though. So unless the reviewer catches it, it ends up on the site.

I think, rather than make the markdown parser look for markdown inside of HTML tags, we should add a parser instruction to turn `note:` into an `<aside>`? I think that would go in this file: https://github.com/GoogleChrome/web.dev/blob/master/lib/deps/markdown.js

**Comment by robdodson** [comment]
This is fixed in the v1 branch using the new `{% Aside %}` shortcodes.
