### ISSUE TITLE
Anchor Tag Outline should be 0.

### ISSUE THREAD

**Issue by helloankit** [GoogleChrome/web.dev#5671]
**Describe the bug**

**To Reproduce**
1. Go to 'https://web.dev/'
2. Click on any anchor tag
3. See error

Even if this design decision is conscious, it should not apply to images that are wrapped under an anchor tag. 

**Expected behavior**
Outline on anchor elements while they are in focus is not necessary and is an aesthetic defect. However in case of keyboard navigation, the outline can be shown to represent the focused element, But during click event, it is not at all necessary.

**Screenshots**
![image](https://user-images.githubusercontent.com/61384771/122602844-1b318e80-d091-11eb-968e-8c6777aff660.png)
![image](https://user-images.githubusercontent.com/61384771/122603136-9004c880-d091-11eb-96be-3d4d297325d8.png)

**Additional Notes**
I have checked the code of web,dev and while running the code locally, I have not encountered this issue. It only exists on the production instance of the application. Please let me know if this issue exists and is not intentional so that I can work toward the required fixes and will raise a PR.

**Comment by MichaelSolati** [comment]
@robdodson I'm down to take over this issue (and it looks like @codebriefcase is too), I think we just need to confirm, is intended behavior?

**Comment by robdodson** [comment]
I think the outline should display on keyboard focus but not when you are mouse clicking the items. I think we load the focus-visible polyfill which should let us handle this scenario. Since it only happens in prod I'm wondering if purgecss is removing one of our styles and if we need to add a comment to tell it to ignore the style. The first place to look would be to see if "focus-visible" appears in the css anywhere.
