### ISSUE TITLE
📝 [LearnCSS] Possible mistake in Z-index CodePen

### ISSUE THREAD

**Issue by vegerot** [GoogleChrome/web.dev#5737]
### What page(s) need to be updated?

https://web.dev/learn/css/z-index/#stacking-context

https://codepen.io/web-dot-dev/pen/JjErOXV?editors=1100

### Why is this update needed?

I was confused while looking at the styles, because I don't see any Z-indices listed.  To confirm, I opened up DevTools and couldn't find any z-index references in this example.

**Comment by tannerdolby** [comment]
I don't think this is a mistake but nonetheless is a bit confusing. You'd expect to see `z-index` properties being used in the CodePen examples stylesheet since the "Stacking context" section mentions explicit numerical `z-index` values in the example. That being said, the result is the same with/without the `z-index` properties because the browser is using the document source order to dictate `z-index` instead. 

> If no z-index is set on your elements then the default behaviour is that document source order dictates the Z axis. This means that elements further down the document sit on top of elements that appear before them.

Since the text content within [Stacking context](https://web.dev/learn/css/z-index/#stacking-context) does mention numerical `z-index` values like 1, 999, 2. 

> In this example, the first parent element has a z-index of 1, so creates a new stacking context. Its child element has a z-index of 999. Next to this parent, there is another parent element with one child. The parent has a z-index of 2 and the child element also has a z-index of 2.

The main goal of this section (after reading the page a few times back) is to highlight how a stacking context aka group of elements with a common parent will move up/down the Z axis within their specific stacking context.

It does from a reader standpoint make it seem like the css should contain: `.top { z-index: 1;  }`, `.inner { .z-index: 999; }`, and `.bottom { z-index: 2; }` declarations since they are explicitly mentioned in the `<figure>` text and within the 'Stacking context' section.

**Comment by tannerdolby** [comment]
I reckon this could potentially be closed @argyleink 

or opt not to close and maybe attempt to make things more clear that the `z-index` properties won't be added in the CSS for CodePen example and the document source order will simply dictate `z-index`, even though explicit numerical values are mentioned in the `<figure>` text of example and web.dev "stacking context" section underneath example.

**Comment by argyleink** [comment]
> It does from a reader standpoint make it seem like the css should contain: .top { z-index: 1; }, .inner { .z-index: 999; }, and .bottom { z-index: 2; } declarations since they are explicitly mentioned in the `<figure>` text and within the "Stacking context" section, although they aren't explicitly needed to visually highlight the separate stacking contexts.

I've added the styles to the demo 👍🏻 
Better to have them in there, the writing certainly makes it sound like they'll be in there
