### ISSUE TITLE
Responsive images not loaded correctly

### ISSUE THREAD

**Issue by simeonbugarija** [GoogleChrome/web.dev#5756]
**Describe the bug**
I'm trying to implement responsive images, everything works fine when I resize the window, the correct images are loaded, the smaller ones, but when I toggle the device toolbar and switch to responsive mode then it shows always the larger images.

**To Reproduce**
1. Go to 'https://responsive-images-multiple-sizes.glitch.me/'
2. Open Chrome dev tools and toggle device toolbar, select Moto G4 device
3. Reload the page
4. Open network tab and filter images
5. flower1-1080.jpg and flower2-1080.jpg are loaded instead of flower1-480.jpg and flower1-480.jpg

**Expected behavior**
The smaller images should be loaded instead of the larger ones.

**Screenshots**
![image](https://user-images.githubusercontent.com/10814563/124465920-48bb4f00-dd96-11eb-9e2d-a449b3379da9.png)
![image](https://user-images.githubusercontent.com/10814563/124465939-4fe25d00-dd96-11eb-9374-044c594ea5e1.png)

**Comment by tannerdolby** [comment]
The browser is loading what you are telling it too! When you say `sizes="(max-width: 480px) 100vw ..."` your telling the browser when the viewport is less than 480px, it needs `100vw` pixels to describe the final rendered width of the image which is 100% of the relative viewport width, therefore will reach for the largest image source (ie flower-*-1080.jpg).

>  The `sizes` attribute tells the browser how many pixels it needs by describing the final rendered width of our image. Think of sizes as a way to give the browser a bit of information about the page’s layout a little ahead of time, so that it can pick a source before it has parsed or rendered any of the page’s CSS. [serving responsive images](https://www.smashingmagazine.com/2014/05/responsive-images-done-right-guide-picture-srcset/)

I would update the `sizes` attribute to make sure the browser knows how many pixels it should expect and therefore can choose the appropriate image source from your `srcset` attribute. Try changing to the first argument in sizes to `(max-width: 480px) 33.3vw` so the browser only describes a final rendered image width of 33.3% of the viewport width which will be smaller than the `flower-*-1080.jpg` image.

Updated HTML:

```html
<img src="images/flower1.jpg" srcset="images/flower1-480.jpg 480w, images/flower1-1080.jpg 1080w" sizes="(max-width: 480px) 33.3vw, (max-width: 1024px) 480px, 100vw">
```

I'm not entirely sure if there is a web.dev page related to your issue here since there wasn't an associated, but I hope this helps @simeonbugarija !

**Comment by robdodson** [comment]
@simeonbugarija I think what's tripping you up is the device emulation and device pixel ratio.

On a retina display, there are more physical pixels packed into the screen, so you need to multiply your image dimensions by the relationship of the physical pixels to the logical pixels. https://developer.fastly.com/reference/io/dpr/ The relationship of the physical to the logical pixels is the device pixel ratio or dpr. It's usually a multiplier like 2x or 3x.

So if your design calls for a 200px wide image, but you're on a 2x display, then you actually need to use a 400px wide image.

The browser knows the dpr for the user's display, so when it's calculating which srcset image to use, it takes the dpr into account. On the Moto 4G, the dpr is 3x (you can see that devtools emulates this).

![image](https://user-images.githubusercontent.com/1066253/127073155-e2b96d0b-1626-45d4-8194-1c524f92a2f1.png)

So it's saying—"The screen is 480px wide, but I need an image that's 480px * 3 for it to not be blurry. So I'll use this 1080 version since it's the best match."

You can change the device emulation so it lets you modify the DPR.

Click the three dot menu in the top right and say 'Add device pixel ratio'

![image](https://user-images.githubusercontent.com/1066253/127073302-3a224fc2-cd3c-48a0-a36e-ed6bd9ecce1e.png)

Then change the device dropdown to 'Responsive', set the width to 480px, and set the DPR to 1. Then when you refresh the page you should see that it is requesting the 480px image.

**Comment by simeonbugarija** [comment]
@tannerdolby @robdodson thanks for the explanation!
