### ISSUE TITLE
Conclusion page [Learn Css]: name of contributors are not rendering.

### ISSUE THREAD

**Issue by Am1tgupt4** [GoogleChrome/web.dev#5797]
**Describe the bug**
Name of contributors are not rendering.

**To Reproduce**
1. Go to https://web.dev/learn/css/conclusion/
2. Scroll down to 'Brought to you by #'
4. Check contributors name "undefined undefined"

**Expected behavior**
Contributors name should be there.

**Screenshots**
<img width="1271" alt="bug" src="https://user-images.githubusercontent.com/33304344/125585850-90d05790-f1a2-4072-887f-2226c2cb9923.png">

**Comment by tannerdolby** [comment]
I did a `{{ author | dump }}` to see if the `name` property existed since it was being depended on in 
```
{%- set authorName = author.name.given + ' ' + author.name.family -%}
```
and as expected the `author.name` property wasn't defined which explains the "undefined undefined" because both `author.name.given` and `author.name.family` aren't defined.

Here is the first `author` object from `set author = authorData[item]`
```
{"homepage":"https://piccalil.li/","github":"andy-piccalilli","twitter":"piccalilli_","image":"image/foR0vJZKULb5AGJExlazy1xYDgI2/KgpVYUM3YJiVTASm4RTB.jpeg"}
```

as we can see the `name` or `description` properties don't exist in `author`. I'm not sure where exactly the data source is for each object in `authorData` but the names being undefined can be explained by the author object missing the properties it expects to receive values from.

<img width="922" alt="Screen Shot 2021-07-15 at 3 20 24 AM" src="https://user-images.githubusercontent.com/48612525/125772565-94e2710f-89b5-475b-9466-15e2b68ce012.png">

**Comment by tannerdolby** [comment]
I'm not entirely sure if the `name` and `description` are coming from eleventyComputed (actually couldn't find with `git grep -n ""`) anything the defined a `name` property. The `description` and underlying `author` object 

```js
/** @type AuthorsItem */
    const author = {
      ...authorData,
      data: {
        date,
        hero: image,
        updated,
      },
      description: `i18n.authors.${key}.description`,
      elements,
      href,
      image,
      key,
      title: `i18n.authors.${key}.title`,
      url: href,
    };
```

seems to have all the stuff we need, but still a bit perplexed why the `name` and `description` have dissapeared when we iterate over the collection in `author-stack.njk`

**Comment by tannerdolby** [comment]
Now that #5823 has landed, I reckon this is ready to be closed as well @MichaelSolati

**Comment by MichaelSolati** [comment]
I agree, and thank you for being so I'm top of this! And all the other related issues 😁

**Comment by tannerdolby** [comment]
Your welcome! I'm glad to help 🎉
