### ISSUE TITLE
Getting terrible performance results from Australia.  Running lighthouse via Chrome audits tab give much better results.

### ISSUE THREAD

**Issue by simonwaw** [GoogleChrome/web.dev#593]
We host a site on AWS in Sydney using EC2/S3.  (Our site is only targeting AU users)

Running Chrome audit tools - we get result in the high 70s.

However when we run a web.dev audit - we get very slow TTFB and long download times to AWS S3 Buckets hosted in the Sydney Region this gives us scores of <15....

Is this test taking into account location?

**Comment by robdodson** [comment]
Good question. It may be possible that the distance between where LH is being run, and your servers could affect the scores.

It's also worth mentioning that there's a bug that just went out in the recent version of the LH service that is really affecting performance scores (I think web.dev's own score fell by ~30 points because of it).
https://github.com/GoogleChrome/lighthouse/issues/7141

**Comment by robdodson** [comment]
It may be worth noting that (I think) the LH servers might be in the U.S.
So, if your infrastructure is serving from Syd when the requests are coming from the U.S. then the site really may be that slow for visitors outside of Aus.

**Comment by robdodson** [comment]
I just spoke with the Lighthouse team who told me they run servers in the following locations:

Southcentral US, Eastern US, Western Europe, Central Europe, Northwest Europe, Southeast US, Central US, Northwest US

**Comment by simonwaw** [comment]
@robdodson thanks for the feedback and confirmation of the location of servers.   Looks like the latency is killing our score.  Thanks for your help.
