### ISSUE TITLE
Update browser support mentions in the content

### ISSUE THREAD

**Issue by mihajlija** [GoogleChrome/web.dev#6003]
#5665 just landed support for embedding compat tables. Opening this issue to track the progress of replacing any plain text browser support tables with the embedded one.

**Comment by jpmedley** [comment]
Given the scope, I'm guessing this will be a group effort. 

All: 

- Make sure the MDN pages exists before adding the component. For features in origin trials, just assume that it doesn't because it won't.
- If you find that a page is missing, let me know so that I can prioritize it in the backlog work. 

You can use an app that I built for a quick way to verify whether something is on MDN. 

1. Install [MDN Helper](https://github.com/jpmedley/mdn-helper). 
2. Change to the install directory
3. Run this command and follow the on-screen instructions:
    `npm run find idl `_anyPartOfInterfaceName_` -- -p`
    * This only takes interfaces, but shows you the interface members.
    * It takes any part of an interface name. For example using 'service' as the search param will let you chose from any interface containing that word. 
4. Follow the on-screen instructions.

**Comment by jpmedley** [comment]
@rachelandrew Here's another example of where the stale bot overcorrects.

**Comment by AaronForinton** [comment]
@rachelandrew I'm up to this ticket - is there any way I can support on this one?

**Comment by rachelandrew** [comment]
@AaronForinton yes quite possibly. On newer posts we use the browser compat component (you can see that listing browser support here: https://web.dev/web-platform-09-2022/#container-queries) and we really want to update old posts to use that as it automatically updates.

Quite possibly in finding these we'll also uncover more things that should be moved to d.c.c. due to only being supported in Chrome. I'll pull together some instructions in our working doc.

**Comment by AaronForinton** [comment]
I'll be working on this in stages and attaching the last PR of my sweep to close this issue. I'll put the others in the comments starting with the first: 

https://github.com/GoogleChrome/web.dev/pull/9071

**Comment by AaronForinton** [comment]
The second PR for this work is #9073

**Comment by AaronForinton** [comment]
Third PR: #9074

**Comment by AaronForinton** [comment]
PR 4: #9086
