### ISSUE TITLE
Change content directory structure to include language code

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/web.dev#623]
Feature request related to #568.

In order to bring i18n to web.dev, we'd like to change directory structure similar to Web Fundamentals.
Current structure is `/content/<actual content>` which needs to be `/content/<lang>/<actual content>`.

**Comment by robdodson** [comment]
Just to keep track of the work.

Ewa has been migrating the site over to use 11ty.io and we're currently generating the english content into a `content/en` directory.

**Comment by robdodson** [comment]
Fixed in the latest version. We now have language directories, but only `en/` so far.

There are places where we still hardcode the `en/` path like in our layouts
https://github.com/GoogleChrome/web.dev/blob/master/src/site/_includes/post.njk#L3

It was easier to do this for now versus using eleventy variable substitution but we can revisit this when we start working on multi language support.
