### ISSUE TITLE
Optimizing resource loading with Priority Hints: importance on script is not valid

### ISSUE THREAD

**Issue by djibe** [GoogleChrome/web.dev#6515]
### What page(s) need to be updated?

https://web.dev/priority-hints/

### Why is this update needed?

When you add `importance="high"`  attribute on a `script` tag, W3C validation throws errors (https://validator.w3.org/ or Vnu.Jar).

The article above doesn't:

- mention this error
- give precisions about the relevance of these errors
- specify if errors in HTML will impact SEO

Thank you very much

**Comment by malchata** [comment]
Since [this is an experimental feature in an Origin Trial](https://developer.chrome.com/origintrials/#/view_trial/365917469723852801) (or is otherwise accessible behind a flag), I would not expect the W3C's validator to consider the `importance` attribute to be valid HTML.

I can't speak for the search team, but it would be my expectation that this would _not_ impact SEO on the basis of the `importance` attribute not passing W3C validation, being that it is an experimental feature that is still in evaluation.

cc: @addyosmani, @yoavweiss, @pmeenan for additional context/information.

**Comment by djibe** [comment]
Hi @malchata , thanks a lot for you answer.
You can close issue as soon as you feel it has been covered.
Best,
