### ISSUE TITLE
content: rename/redirect Compat 2021 to Interop 2021

### ISSUE THREAD

**Issue by foolip** [GoogleChrome/web.dev#6666]
### What page(s) need to be updated?

https://web.dev/compat2021/
https://web.dev/compat2021-midyear/

should be redirected to

https://web.dev/interop-2021/
https://web.dev/interop-2021-midyear/

and have their content updated.

### Why is this update needed?

We have decided to name the continuation of this effort Interop 2022, and in https://github.com/web-platform-tests/interop-2022/issues/3 @jensimmons suggested renaming the current effort as well, because:

> It'll be easier for everyone if we just always call this "Interop [Year]".

### What's the deadline?

Before we announce [Interop 2022] in early/mid-December.

cc @kosamari

**Comment by rachelandrew** [comment]
This is mentioned as compat 2021 in the CDS stuff going out today, so maybe we hold fire on doing this for a couple of weeks and then do the updates?

To be honest, I'm not keen on the interop name as it's only us who say interop, "compat/compatibility" is something actual developers say, but I'm probably a lone grumpy voice on that point.

**Comment by foolip** [comment]
There's no rush to do this right away, waiting for 2-4 weeks would be OK.

I also prefer "compat" since it's the terminology I've seen from developers in free-form survey responses, and what MDN uses, but when we recently discussed among browser vendors that was a minority view. The concern is that "compat" means "site compat" to browser vendors, and expanding it to "browser compat" also wasn't seen as clear enough.

**Comment by rachelandrew** [comment]
@foolip it seems a bit weird to update the name of these articles as their content is very much about 2021 and the work done for compat 2021 in 2021. They are at this point the historical record and we likely want to refer back to them in terms of progress.

I suggest we update them with a note about the name change, once the Interop 2022 article goes live https://github.com/GoogleChrome/web.dev/issues/6799 but otherwise maintain them as the historical record of 2021. That appears to be the approach mentioned here https://github.com/web-platform-tests/interop-2022/issues/3#issuecomment-965470559

So I suggest as part of the PR that adds #6799 we add a callout to those articles saying something like, the compat project has been renamed interop, and you can find the Interop 2022 article here.

**Comment by foolip** [comment]
@rachelandrew agreed, I took a too literal interpretation of https://github.com/web-platform-tests/interop-2022/issues/3 at first, and adding notes seems like the better approach.

**Comment by rachelandrew** [comment]
cool, well I'll leave this open as a reminder to do this as part of the Interop 2022 post going live.
