### ISSUE TITLE
If DOMParser.parseFromString is an actual unsafe XSS sink...

### ISSUE THREAD

**Issue by franktopel** [GoogleChrome/web.dev#6890]
https://github.com/GoogleChrome/web.dev/blob/b3b8b39a6bd2bbc58968a767176967b7e0c46354/src/site/content/en/blog/trusted-types/index.md?plain=1#L75

... then potentially [DOMPurify's approach of sanitizing](https://github.com/cure53/DOMPurify/blob/main/src/purify.js#L728) is by itself a security risk: 
```js
    if (NAMESPACE === HTML_NAMESPACE) {
      try {
        doc = new DOMParser().parseFromString(dirtyPayload, PARSER_MEDIA_TYPE);
      } catch (_) {}
    }
```

Because your article [also suggests DOMPurify as a sanitization lib](https://github.com/GoogleChrome/web.dev/blob/b3b8b39a6bd2bbc58968a767176967b7e0c46354/src/site/content/en/blog/trusted-types/index.md?plain=1#L206), please clarify.

@koto Could you please take a look?

**Comment by cure53** [comment]
https://html.spec.whatwg.org/multipage/dynamic-markup-insertion.html#dom-domparser-parsefromstring-dev

> Note that script elements are not evaluated during parsing, and the resulting document's encoding will always be UTF-8.

**Comment by franktopel** [comment]
It's not as if `<script>` elements are the only bad things that can be contained in `dirty`.

**Comment by cure53** [comment]
Then maybe this helps resolving the mystery :) There is no scripting here that could lead to XSS.

> Since document does not have a browsing context, scripting is disabled.

https://html.spec.whatwg.org/multipage/dynamic-markup-insertion.html#dom-domparsersupportedtype-texthtml

**Comment by franktopel** [comment]
Is the same true for your [alternative document creation method](https://github.com/cure53/DOMPurify/blob/b9dbc69b88fbcacbe0b43c4eff30fed39d892652/src/purify.js#L733)?

**Comment by koto** [comment]
`DOMParser.parseFromString` requires a `TrustedHTML`, because that function will create a DOM tree, and you could extract nodes from that tree - e.g. ones containing 'onclick' or 'srcdoc` attribute nodes. These would then execute as soon as they are attached to the main document. 

At the same time, it's on of the few ways to actually obtain an inert tree, for the purposes of its sanitization, which is what DOMPurify is doing. You are technically correct, DOMPurify's use of DOMParser *is* a security risk, because that library may have a buggy sanitization. Trusted Types in this case tell you that this library does a security sensitive operation. Which is expected, sanitizers are supposed to do that, and TT just let you discover which libraries are in fact responsible for HTML sanitization in your application. 

In the long run, DOMPurify could use the native sanitizer API in place of DOMParser, and TrustedHTML would not be neccessary, and the security risk (w.r.t. DOM XSS) would be completely gone, as the native browser API instead of brilliant and life-saving, yet complex and potentially buggy logic of DOMPurify would be guaranteeing that scripty payloads are stripped from the tree.

**Comment by cure53** [comment]
> Is the same true for your [alternative document creation method](https://github.com/cure53/DOMPurify/blob/b9dbc69b88fbcacbe0b43c4eff30fed39d892652/src/purify.js#L733-L740)?

Yes

**Comment by franktopel** [comment]
> `DOMParser.parseFromString` requires a `TrustedHTML`

Then that means that DOMPurify itself must declare a policy, and that policy is probably passing the dirty string unmodified.

**Comment by franktopel** [comment]
Has anyone ever investigated attack vectors on elements not in a live document?

**Comment by cure53** [comment]
Yes, for many years in various browsers. The last bypass we spotted was Java Applet related - other than that, there are no known issues at this moment I am aware of.

**Comment by koto** [comment]
To add to @cure53, this (TT policy that blesses anything) is practically unavoidable. That's currently the only way to sanitize a string into DOM nodes. The only alternative that would be "safe by construction", and not because of DOMPurify's scrutiny and know-how, would be if DOMPurify shipped its own HTML parser and then created only safe nodes (safe, because TT won't let you create "bad" nodes) out of its emulated DOM tree. Which we know is not the correct way to tackle sanitization, nor efficient nowadays. 

IIRC there was also some Safari bug a few years back, where inert doc wasn't inert at all.

**Comment by cure53** [comment]
Oh, haha yeah, the Webkit regression, that was nasty :D

**Comment by franktopel** [comment]
Okay, thanks for taking the time and elaborating. Still feels kinda bad to have to rely on browser implementations here, but that's the way it is.

**Comment by koto** [comment]
Yup. Sanitizer API, that's our only way out.

**Comment by franktopel** [comment]
Would be great if other browser vendors would start implementing trusted types, at all. Safari does not even seem to support the CSP setting.

![image](https://user-images.githubusercontent.com/10668603/143440781-ed3ff335-c451-4a50-8f8f-42cfcc9a520f.png)

**Comment by koto** [comment]
I agree :) Your voice might help - https://github.com/mozilla/standards-positions/issues/20

**Comment by franktopel** [comment]
I've at least asked: https://github.com/mozilla/standards-positions/pull/291#issuecomment-979172514

**Comment by franktopel** [comment]
Closing this as I trust your explanations.
