### ISSUE TITLE
Sign in with Google button on the measure page doesn't work for some users.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#707]
Saw a report on Twitter about this but I'm not able to reproduce on my devices. Need to get more info.

https://twitter.com/juristr/status/1103946827827691521

**Comment by juristr** [comment]
Using: Version 73.0.3683.56 (Official Build) beta (64-bit)

Here's a video where I try to reproduce it.
https://www.youtube.com/watch?v=Y6jp0133GDQ&feature=youtu.be

The bug is kinda weird. As you can see it seems as if the link isn't set properly on the button (which seems to happen dynamically). When I hover the button, you can see the link being shown at the lower-left. In the video I continuously try to click the button, but nothing happens. Also reloading (CMD+Shift+R) doesn't seem to help. 
Since in the console there were a bunch of errors related to the `sw.js` file, I tried to unregister the service worker which didn't seem to help initially, but then after some time the link was correct and worked 🤔. So I don't even know it's related to that.

Clicking the button then, I got redirected to the login, clicked the browser back to go again to web.dev, and had the same issue again. Really strange. Not sure this was helpful 😅

**Comment by robdodson** [comment]
wow yeah super weird but helpful, thank you! I'll see if we can get to the bottom of things.

**Comment by robdodson** [comment]
oh yeah I'm able to reproduce it in an incognito window. I'll take a look at the service worker.

**Comment by robdodson** [comment]
I believe this should be fixed now. Let me know if you still see issues and thanks for the report!
