### ISSUE TITLE
https://web.dev/get-started-optimize-react/ -> embed react app does not work

### ISSUE THREAD

**Issue by DanielOberlechner** [GoogleChrome/web.dev#7126]
**Describe the bug**
https://web.dev/get-started-optimize-react/
![Bildschirmfoto 2022-01-05 um 18 20 34](https://user-images.githubusercontent.com/10922763/148260801-6cefef43-d90b-4029-a755-e51b10003018.png)

**To Reproduce**
Go to https://web.dev/get-started-optimize-react/ and scroll down

**Expected behavior**
The embed code should show a react website

**Comment by rachelandrew** [comment]
@housseindjirdeh do you know what happened to the Glitch in this article?

**Comment by thinkverse** [comment]
> do you know what happened to the Glitch in this article?

This question is a bit old, but it seems the Glitch [project](https://glitch.com/~new-create-react-app) - "~new-create-react-app", has been suspended[^1].

[^1]: ["Project Suspensions"](https://help.glitch.com/kb/article/72-project-suspensions/). Glitch Helpdesk.

**Comment by housseindjirdeh** [comment]
Sorry for the delay. I'm not really sure why the Glitch is failing here, and the error message I see is a bit cryptic:

<img width="543" alt="Screen Shot 2022-04-19 at 11 15 50 AM" src="https://user-images.githubusercontent.com/12476932/164037681-a48261a0-23ee-4eba-9282-7e50e522f20b.png">

@rachelandrew Since this is an introductory article, I would be okay with removing the Glitch entirely or replace it with a screenshot of the app's file structure. Wdyt?

**Comment by AaronForinton** [comment]
Hi @rachelandrew @housseindjirdeh - I'm happy to be the one to replace it with the screenshot if that can be procured.

**Comment by dstmarthe** [comment]
It's working for me now on Chrome and Firefox. We're moving to a new platform and issue tracker either way and content on this site is now frozen. If this Glitch error persists after the move then I encourage you to report it to the new issue tracker at https://issuetracker.google.com/issues?q=status:open%20componentid:1400680&s=created_time:desc
