### ISSUE TITLE
Pattern set does not display that correct header text

### ISSUE THREAD

**Issue by khempenius** [GoogleChrome/web.dev#7348]
**Describe the bug**
The header that "Layout Patterns" should say "Web Vitals Patterns"

**Screenshots**
https://web.dev/patterns/web-vitals-patterns/
![Screen Shot 2022-02-11 at 5 25 02 PM](https://user-images.githubusercontent.com/6076184/153679164-bb06c14c-1e44-4596-a41c-b9af856722a6.png)

**Comment by jeffposnick** [comment]
Looking closer at this, would it make sense to use a more generic heading here, instead of repeating either "Layout Patterns" or "Web Vitals Patterns"?

I could imagine just hardcoding "Choose a pattern" here, or something similar, since this is always the header for a ToC?

<img width="638" alt="Screen Shot 2022-02-14 at 1 50 26 PM" src="https://user-images.githubusercontent.com/1749548/153927418-4f694db9-a22a-46d1-8311-bb7f581241d7.png">

**Comment by khempenius** [comment]
Yes, that would work. How about "Table of contents"?

**Comment by jeffposnick** [comment]
My concern is that having an "All" entry doesn't really fit with the wording "Table of contents."

I don't know what the historical context is here—maybe there was some sort of UX work done initially here that could inform a change?

CC: @una in case she has an opinion or context to share, as this would effect https://web.dev/patterns/layout/ as well.
