### ISSUE TITLE
Learn CSS: 27 : missing options in 4th question of the QUIZ

### ISSUE THREAD

**Issue by kalitine** [GoogleChrome/web.dev#7394]
**Describe the bug**
No options for answering in question 4 of the QUIZ.

**To Reproduce**
1. Go to [Learn CSS -> Backgrounds -> QUIZ -> Question 4](https://web.dev/learn/css/backgrounds/#the-background-shorthand)

**Expected behavior**
Get options.

**Screenshots**
![image](https://user-images.githubusercontent.com/6207427/155149106-a378df1c-62d6-4302-9f0f-70d5b35ed927.png)

**Comment by jeffposnick** [comment]
This question has a `type: think-and-check`: https://github.com/GoogleChrome/web.dev/blob/1bfe53353aeacbe0ab456c1f17dc8528a967fbf8/src/site/content/en/learn/css/backgrounds/backgrounds.assess.yml#L47-L54

I assume that means it's not meant to receive any input from the person viewing the page, and is purely a self-check.

Perhaps the UI could be tweaked for `think-and-check` questions in some way to make it clearer that there's no input expected?

**Comment by tannerdolby** [comment]
> I assume that means it's not meant to receive any input from the person viewing the page, and is purely a self-check. Perhaps the UI could be tweaked for think-and-check questions in some way to make it clearer that there's no input expected?

As a reader of the article for the first time, I felt that Q4 was purely a self-check like you mentioned. But at first I did think "wheres the options to choose from?" since Q1-Q3 and Q5 do have options displayed.

That being said, I do think the UI could benefit from a bit more "descriptive text" that helps users to understand the question purely wants them to think about the steps it would take to recreate the example rather than select any options hence why the options aren't displayed (display: none for that unordered list in the stylesheet).

<img width="1224" alt="Screen Shot 2022-03-04 at 11 11 47 PM" src="https://user-images.githubusercontent.com/48612525/156872941-b7b35f37-e103-4b11-a764-e40847c0d9da.png">

### Thoughts
In school/college/etc, when faced with a question where no input is required, I usually took it as we needed to either:

1.) Think aloud (or silently) the answer to given question and be prepared to "implement" or "produce" the solution on our own (separately from the quiz)
2.) Write down the steps to arrive at solution on a piece of paper (or notepad/ide/etc)

And specifically for these questions here on web.dev that have the `think-and-check` question type, it wouldn't be a out of the question to create a [Codepen](https://codepen.io) demo and link that in the question description. For example maybe something like,

<img width="829" alt="Screen Shot 2022-03-04 at 11 29 37 PM" src="https://user-images.githubusercontent.com/48612525/156873359-936d9eea-9062-4b1e-ac73-75d289e82c55.png">
