### ISSUE TITLE
BrowserCompat widget is displaying pre-release browsers 

### ISSUE THREAD

**Issue by rachelandrew** [GoogleChrome/web.dev#7447]
At some point BCD has started listing pre-release versions of browsers, therefore making it look as if things are available if you don't happen to know the version number that is stable. This makes it look as if things are usable when they are not.

I am wondering if there is anything we can do with our use of the Compat component to filter against stable browsers. The data does include if a browser is current or beta. This is the data for Safari https://github.com/mdn/browser-compat-data/blob/main/browsers/safari.json

You can currently see the problem on the What's New post for Feb releases, it looks like things are available, unless you know that Safari 15.4 is a beta: https://web.dev/web-platform-02-2022/

**Comment by tannerdolby** [comment]
Hello @rachelandrew!

> At some point BCD has started listing pre-release versions of browsers, therefore making it look as if things are available if you don't happen to know the version number that is stable. This makes it look as if things are usable when they are not.

I completely agree. While reading over https://web.dev/web-platform-02-2022/, I just assumed the displayed version number was stable if it had the green checkmark. 

Like you suggested, since the data is available for checking if a browser is current or beta:

```json
"15.4": {
    "status": "beta",
    "engine": "WebKit",
    "engine_version": "613"
}
```

We could add a `status` check in the "check" functions (compatAria, compatProperty, compatValue) which can then determine whether the Compat component returns the added version if the browser is stable, otherwise "small x" if the browser is unstable.

**Comment by rik** [comment]
While reading https://web.dev/state-of-css-2022/, I also noticed that the widget does not look at Experimental Flags.

Just to highlight one issue, [color-mix()](https://web.dev/state-of-css-2022/#color-mix()) is [only available behind Flags](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix#browser_compatibility) in Firefox 88 and 15. But the widget displays a green background.
