### ISSUE TITLE
Images overflowing and colliding with the TOC

### ISSUE THREAD

**Issue by mihajlija** [GoogleChrome/web.dev#7462]
See the screenshot below from https://web.dev/samesite-cookies-explained/ on a 16" screen.

<img width="1324" alt="Screenshot 2022-03-07 at 13 22 07" src="https://user-images.githubusercontent.com/17127567/157109923-f1b30627-f18f-41e6-b770-fd8cae07dd57.png">

**Comment by jeffposnick** [comment]
It looks like there are some hardcoded widths in the `style` attribute for that image that are too large.

I've also been bothered by this page because of the `>` and `<` characters in the fenced code block, so the page technically has invalid HTML. Our HTML minifier steps always errors on these pages because of that.

I can file a PR to fix both (in `en` and the other translations as well).

**Comment by mihajlija** [comment]
@jeffposnick I'll be refactoring this doc in the next couple of months, but the fixes will rollover so please do :)
