### ISSUE TITLE
Broken styling on Developer Newsletter form

### ISSUE THREAD

**Issue by LoncarKlemen** [GoogleChrome/web.dev#7638]
**Describe the bug**

On web.dev website, under Developer Newsletter form, first two inputs are missing type on input element, for that reason styling is not applied.

**To Reproduce**
1. Go to https://web.dev/ and scroll down to the form
2. Inspect first two input elements (first name, last name)

**Expected behavior**
- Form should be styled.

**Screenshots**
<img width="883" alt="Screenshot 2022-04-04 at 13 47 52" src="https://user-images.githubusercontent.com/48187914/161537483-fa6a1d4b-0c42-4618-aceb-d87dd903a00d.png">

**Comment by jeffposnick** [comment]
The `type="text"` is included in our HTML source: https://github.com/GoogleChrome/web.dev/blob/707e9c29464b30129d9396592ade11bd2eb269ee/src/site/_includes/partials/subscribe.njk#L11-L12

It looks like our HTML minification step is removing that attribute, since it's effectively redundant. We should adjust the relevant CSS accordingly.
