### ISSUE TITLE
Using `Aside` directive in Markdown list context leads to invalid HTML

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/web.dev#7640]
**Describe the bug**
The articles that are using `Details` directive are broken.

**To Reproduce**
1. Go to https://web.dev/security-headers/ or https://web.dev/strict-csp/
2. Scroll down to the bottom

**Expected behavior**
You can see the bottom of the page, but it's actually terminated at `Details` directive.

**Comment by jeffposnick** [comment]
This is due to a combination of the Markdown list parser and the `{% Aside %}` directive leading to invalid HTML output. The new HTML minifier we switched to in #7532 treats invalid HTML differently than the old minifier.

If you want to see the invalid HTML yourself, you can run `npm run eleventy` locally, then take, e.g., `dist/security-headers/index.html` and paste it into https://validator.w3.org/#validate_by_input. You'll see something like:

<img width="1398" alt="Screen Shot 2022-04-04 at 9 52 09 PM" src="https://user-images.githubusercontent.com/1749548/161663946-a9cf2d2d-8218-4a70-845e-5da075a5ec43.png">

There are a few options for resolving this:

- We can get rid of the `<li>` elements created by the Markdown processor, by switching these from numbered items to `<h4>`s via `####`:

https://github.com/GoogleChrome/web.dev/blob/244e5a0dac60042d3ef5dacd6387adf5664d98c7/src/site/content/en/secure/security-headers/index.md?plain=1#L355

- We can keep the numbered items, but don't use any `{% Aside %}` directives inside of them:

https://github.com/GoogleChrome/web.dev/blob/244e5a0dac60042d3ef5dacd6387adf5664d98c7/src/site/content/en/secure/security-headers/index.md?plain=1#L379-L385

- We can find out some way to massage the Markdown list parser + `{% Aside %}` output to produce valid HTML, but that will probably take longer.
