### ISSUE TITLE
Firefox: bugs in measure URL section

### ISSUE THREAD

**Issue by co16353sidak** [GoogleChrome/web.dev#773]
1. the buttons alongside the the search url have text not centered to the button.
2. the `X` button seems to also be top-aligned while t should be inline with the text.

URL: https://web.dev/measure
 
Screenshot: <img width="513" alt="Screenshot 2019-04-05 at 11 04 22 PM" src="https://user-images.githubusercontent.com/35738138/55646096-e7435900-57f7-11e9-932b-47097dbf0bfd.png">

(could be added to issue #751 checklist)

**Comment by robdodson** [comment]
This is fixed and should roll out in the next release.

**Comment by alexandersandberg** [comment]
@robdodson There still seems to be an issue with the vertical alignment of the 'Remove URL' icon. Tested in Opera, Safari, Firefox, and Chrome, and all show the same misalignment.

![Screenshot of misaligned icon](https://user-images.githubusercontent.com/35671299/61595608-66b73580-abf9-11e9-9f17-dca85876ffbc.png)

(I'm assuming the fixes you mentioned are live as the button text is now aligned properly. I could not check this locally, however, since the measure feature won't work with localhost.)

**Comment by robdodson** [comment]
Oh I bet they're not live yet if you're still seeing issues in Firefox. It looks like the last release of the frontend may have been 10 days ago so my change didn't quite make it. Kind of a long story but for certain components like these our site gets released as part of a bigger piece of Google infrastructure and it can take a week or more to roll out.

**Comment by alexandersandberg** [comment]
I appreciate the explanation! The issue I'm seeing differs a bit from the original one, however, since the button texts are aligned properly, and the X is pushed down slightly—although not completely centered.

I see this in all major browsers on macOS, as well as in Safari on iOS. It might still be the case of the fix not live yet, of course, so I guess it's best to wait and see.

**Comment by robdodson** [comment]
yeah I think the release still hasn't gone out yet so I'll check back the next time I get a notification that the release is going out to confirm it's fixed.
