### ISSUE TITLE
Fonts preload without CORS

### ISSUE THREAD

**Issue by kyliau** [GoogleChrome/web.dev#7770]
**Describe the bug**
See console errors in screenshot below.
Also, notice that something seems off about the minified HTML - missing quotes, missing spaces, etc.

**To Reproduce**
1. Go to https://web.dev/optimize-webfont-loading/ (or any other page, really)
2. Open devtools
4. See error in console

**Expected behavior**
No errors in console.

**Screenshots**
<img width="1840" alt="Screen Shot 2022-04-21 at 1 28 49 PM" src="https://user-images.githubusercontent.com/2941178/164551116-4f5eda15-dbd0-480c-9c5b-6e92c7bd6bb9.png">

Source looks correct:

https://github.com/GoogleChrome/web.dev/blob/e5e87746c542aa87d7314681f1bb0037035c4e28/src/site/_includes/partials/head.njk#L19-L23

Perhaps something went wrong during the build?

**Comment by jeffposnick** [comment]
Thanks for reporting; this is due to https://github.com/wilsonzlin/minify-html/issues/81

We'll address it in the meantime by explicitly using `<link crossorigin="anonymous" ...>` instead of `<link crossorigin ...>` in our source.

(The other spacing issues are side-effects of the minification, but they don't impact how the HTML is parsed or interpreted by the browser.)

**Comment by jeffposnick** [comment]
Sigh, no, `<meta content=width= device-width,initial-scale=1.0 name=viewport>` is due to the HTML minifier as well. Thanks for pointing that out. It looks like it was discussed at https://github.com/wilsonzlin/minify-html/issues/44 and I need to figure out why our config is not producing the expected output.
