### ISSUE TITLE
content: Recommend use of min-height when reserving space for ad slots

### ISSUE THREAD

**Issue by JDishman** [GoogleChrome/web.dev#7956]
### What page(s) need to be updated?

https://web.dev/optimize-cls/#ads-embeds-and-iframes-without-dimensions

### Why is this update needed?

Publishers may hurt monetization by reserving a fixed height for their ad slot. Ads delivered may be cropped when a fixed height is set, and some ad requests can use signals like size of parent containers to determine if larger ads can safely be served to an ad slot. Setting a min-height instead of a fixed height allows space to be reserved for an ad slot to reduce cumulative layout shift, while also allowing larger ads to serve without the risk of cropping, as well as allowing for ad slot expansion features.

Guidance could be something along the lines of:

> "At times it may make sense to reserve a size smaller than the largest possible ad that could be returned from the ad server, trading off occasional reflow for reduced empty space in the majority of cases. When doing this, however, reserve space with CSS directives like min-height to ensure that if a larger ad is returned it will be able to display fully."

**Comment by tunetheweb** [comment]
I'm reading https://web.dev/optimize-cls/#advertisements and not seeing where we suggest fixed sizes.

We do say "Statically reserve space for the ad slot", but that depends on whether that's possib;e.

In fact I also see specific talk on " reserving the largest possible size for the ad slot" (with the recognition that "it risks having a blank space if a smaller ad creative fills the slot").

And also this:

> This can be as simple as adding a min-height styling to reserve space or, for responsive ad sizings using the new [aspect-ratio](https://web.dev/aspect-ratio/) CSS property in a similar manner to the way browsers automatically use this for images with dimensions provided.

Perhaps the content has changed since you raised this issue, but if not could you let us know exactly what text you risks hurting monetization?
