### ISSUE TITLE
Bullet points inside Aside component is not parsed

### ISSUE THREAD

**Issue by agektmr** [GoogleChrome/web.dev#8202]
**Describe the bug**
Bullet points markdown inside an "Aside" component is no longer parsed as so.
For example, at the bottom of [this page](https://web.dev/same-site-same-origin/), "Important" side has two bullet points but they are rendered as plain texts.

**Screenshots**
<img width="759" alt="Screen Shot 2022-06-19 at 18 25 29" src="https://user-images.githubusercontent.com/218144/174474394-c6990df7-408d-49be-8263-cae57c767fac.png">

**Comment by jeffposnick** [comment]
Unfortunately, we can't go back to that old behavior. This is due to https://github.com/GoogleChrome/web.dev/pull/7648, which was necessary to resolve an issue that could lead to invalid HTML in the final rendered document.

https://github.com/GoogleChrome/web.dev/pull/7712 allows for HTML to be used inside of an `Aside` component, even though Markdown can't be used. So if you translate your `*` to `<ul>` + `<li>`, things would render as expected.

**Comment by agektmr** [comment]
Hmm, if this is not planned to be changed, a lot of existing articles that include markdown syntax within `{% Aside %}` directives should have been broken. I can manually fix articles I authored, but for others, we should probably think about scalable way to fix.

**Comment by agektmr** [comment]
Whoa! Thanks Rachel for taking care of this!
