### ISSUE TITLE
Progressive Web Apps: Going Offline is not working due outdated packages

### ISSUE THREAD

**Issue by lulamprea** [GoogleChrome/web.dev#8253]
After installing the final branch, of https://developers.google.com/codelabs/pwa-training/pwa03--going-offline#0  I found out that there  are several  new versions of the packages  used in the app; among them codemirror is used in editor.js "import { defaultTabBinding } from '@codemirror/commands';" but defaultTabBinding was removed on [@codemirror/commands](https://codemirror.net/docs/ref/#commands) 0.19.0 (2021-08-11).

Could you please let me know the versions of the packages used, so I can run it?

Thank you very much for your help, it will be greatly appreciated.

Luis

**Comment by AaronForinton** [comment]
Hi @petele, let me know if I can support on this one.

**Comment by andreban** [comment]
The [GitHub repo](https://github.com/GoogleChromeLabs/pwa-workshop-codelab) was updated on September 2022, after the issue was filed. It also uses `@codemirror/commands` version `6.1.0`. I tested the branches within in the repo, and all seem to work well. It seems that the issue was fixed after this issue was filed, but the issue itself wasn't updated.
