### ISSUE TITLE
Double check aside styles for color contrast.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#833]
I just noticed the `caution` aside doesn't meet the contrast minimum. Need to circle back and check the others.

**Comment by simevidas** [comment]
Additionally, there are some contrast issues in code blocks. Maybe it‘s finally time that we stop choosing syntax highlighting themes based on appeal and start enforcing strict contrast requirements for them as well.

<img width="612" alt="Screen Shot 2019-10-11 at 8 50 35 PM" src="https://user-images.githubusercontent.com/716405/66677058-2354ec00-ec69-11e9-9db5-80c313ba8df1.png">

**Comment by mfriesenhahn** [comment]
BTW, I already checked the aside colors. Caution is the only one that isn't 4.5:1. (Orange is always a problem.) We'll need to change it to a different hue--maybe `$PINK_700`--since it'll just look brown if we reduce the brightness (e.g., `$ORANGE_900`). The problem, though, is that you lose the color semantics.

I'm wondering if it's worth reconsidering the presentation of the asides--dark text on a pastel background, for example, retains semantic colors while preserving accessibility. Also, it might improve the position of the asides in the visual hierarchy. A default aside is supposed to be _less_ important than the body text, but right now it's pretty assertive.

If anybody's interested, I could mock up some options.
