### ISSUE TITLE
Table of Content ignores first non-roman H2 title

### ISSUE THREAD

**Issue by anaclumos** [GoogleChrome/web.dev#8528]
For non-roman translations, especially when the first title doesn't include any non-roman characters and therefore renders the anchor as `/#`, the table of content ignores the header and doesn't render.

In the below screenshot, "미니앱이 아닌 것들" is an H2 header, but it doesn't contain any roman characters and therefore has an anchor of `/#` and doesn't appear on the table of contents.

<img width="987" alt="Screen Shot 2022-08-15 at 5 46 04 PM" src="https://user-images.githubusercontent.com/31657298/184605140-1a91765c-4cfd-4f54-943f-92a2303b0832.png">

**Comment by matthiasrohmer** [comment]
I did some investigation on this: first I thought our TOC filter breaks, but the problem is a little earlier when markdown gets parsed to HTML.

Our TOC only picks up headlines that have an `id` attribute. 11ty, respectively 11ty's markdown renderer markdown-it, does not generate those by default. We therefore use the markdown-it-anchor plugin with a custom slug function based on [slugify](https://www.npmjs.com/package/slugify) to create those. The problem is slugify can not deal with Japanese characters and hence creates empty strings which prevents the headline from ending up in the TOC.

Way to solve this: we could switch to another slugifier, though most do not support non-latin languages sufficiently, also see https://github.com/sindresorhus/transliterate/issues/1. Also this might potentially break existing deep links if slugs turn to be out slightly different.

Alternative workaround: we also have markdown-it-attrs in place which allows setting explicit attributes on rendered element like so ` ## 미니앱이 아닌 것들 {: #toc-headline }`. This would allow to manually set a latinized slug, which is not ideal from many perspectives.

Forwarding to @devnook for advice 🙂

**Comment by tunetheweb** [comment]
@matthiasrohmer this would also be fixed - perhaps more simply? - by #8263
Though technically probably should URL encode these characters as you have.

**Comment by anaclumos** [comment]
> The problem is slugify can not deal with Japanese characters and hence creates empty strings which prevents the headline from ending up in the TOC.

Just an FYI, this is Korean, not Japanese. https://github.com/GoogleChrome/web.dev/pull/8471

But anyhow, thanks for the work!

**Comment by matthiasrohmer** [comment]
@tunetheweb, true! Haven't thought of configuring slugify, great!

@anaclumos, appreciate the hint, thanks! ☺️ Next time I'll check with Google Translate instead of guessing.
