### ISSUE TITLE
Site works a cross browsers, just recommends to use work box

### ISSUE THREAD

**Issue by PaulKinlan** [GoogleChrome/web.dev#870]
https://web-dev-staging.appspot.com/pwa-cross-browser/

Not sure if the guidance is correct (I can't find it on d.g.c) but the emphasis behind this check is to test your site holistically for cross browser support, and not just focus on offline support.

**Comment by robdodson** [comment]
@PaulKinlan I'm not sure if Michael F. updated this at one point but the doc currently says:

"Test your site in Chrome, Edge, Firefox, and Safari, and fix any issues that appear in each browser.

If your page is a Progressive Web App, consider using Workbox, a high-level service worker toolkit. Workbox is developed against a cross-browser test suite, and when possible, automatically falls back to alternative implementations of features that are missing from certain browsers:

..."

So it _seems_ like it's saying to check that your site works cross browser and then deep dives on workbox because (I think) this is technically in the PWA audits section. I'm not sure what it should say beyond that?
