### ISSUE TITLE
Think about embedding Glitch example into Portals post.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#876]
Related to https://github.com/GoogleChrome/web.dev/pull/862

One way to do this would be to use feature detection, and if the user doesn't have portals enabled, show them the flag to enable it. This could be useful for when Portals is shipping everywhere so folks can just automatically see and interact with them.

**Comment by uskay** [comment]
It does do feature detection even now and show a message but I'll make sure it is more easy to understand so that they could figure out their way easily. I'll work on that.

**Comment by uskay** [comment]
@robdodson Changed the UI a bit to make things obvious. WDYT?
![draft UI of the demo](https://cdn.glitch.com/98449704-33d8-49b2-88f2-aa6d2aeba5d3%2FScreen%20Shot%202019-05-04%20at%2012.13.31.png?1556939687149)

**Comment by robdodson** [comment]
@uskay nice, I think that looks great :)

**Comment by uskay** [comment]
I think I can fix the article just before the flight, will let you know!

**Comment by uskay** [comment]
This is very unfortunate but come to think about it, Portals cannot be used inside iframes by design...
> Cannot use <portal> in a nested browsing context.
![a screenshot of DevTools console error](https://cdn.glitch.com/98449704-33d8-49b2-88f2-aa6d2aeba5d3%2FScreen%20Shot%202019-05-04%20at%2018.10.30.png?1556961061414)

- https://wicg.github.io/portals/#the-portal-element
- https://github.com/web-platform-tests/wpt/blob/master/portals/portals-activate-inside-iframe.html

**Comment by robdodson** [comment]
ah ok. No worries :) We'll make sure the links to the examples stand out. Thank you for looking into it @uskay!
