### ISSUE TITLE
content: Update bfcache article to clarify `unload` ineligibility on mobile

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/web.dev#9044]
https://web.dev/bfcache/#never-use-the-unload-event says:

> Chrome and Firefox have chosen to make pages ineligible for bfcache if they add an unload listener, which is less risky but also disqualifies a lot of pages.

AFAIK this isn't necessarily true. At least in Chrome, a page that uses `unload` may still be eligible for bfcache if the user is on mobile. It'd be good to clarify this behavior because I don't think this exception is documented anywhere.

cc @philipwalton @tunetheweb

**Comment by philipwalton** [comment]
I'm okay with making some changes to this text to be more correct, but I'd also caution against being too specific because:

1. Things may change without us realizing it, and
2. The whole point is we want to discourage use of the `unload` events regardless

So whatever we do say, we should still emphasize that either the `unload` event is already being ignored, so it's unreliable and shouldn't be used, or it disqualifies a page from bfcache so it's bad for performance and also shouldn't be used.
