### ISSUE TITLE
Tabbed mode video not rendering [iOS]

### ISSUE THREAD

**Issue by jespertheend** [GoogleChrome/web.dev#9094]
**Describe the bug**
The image in the tabbed mode isn’t visible. On iOS anyway, not sure about other platforms.

**To Reproduce**
1. Go to https://web.dev/learn/pwa/windows/
2. scroll to 'tabbed mode'

**Expected behavior**
An image to render

**Screenshots**
![768EB2DF-22BA-4778-9851-6EEF48E5CBD6](https://user-images.githubusercontent.com/2737650/202931992-6b16682f-7661-4794-9c43-b0a53fedd480.png)

**Comment by AaronForinton** [comment]
The reason this file isn't rendering is because it's a .webm ([link here])(https://storage.googleapis.com/web-dev-uploads/video/8WbTDNrhLsU0El80frMBGE4eMCD3/JwN0btyXFGiT9oPFh2qJ.webm). 

For reference, I'm using an iPhone with iOS 15.6.1 and you can see from my [http://html5test.com/s/9266615eb92e7539.html](results here) that Safari won't render WebM. 

I'm going to check with the powers that be if it might be better to convert this to an MP4.

**Comment by AaronForinton** [comment]
@jespertheend Once the associated PR is merged you'll be able to see the video. It has been converted to MP4.

**Comment by jespertheend** [comment]
Thanks for the quick fix! I just tried the preview url out on iOS, it seems to display the first frame but it doesn't play.
