### ISSUE TITLE
Images comparison of MIME Type filename vs http-header content-type

### ISSUE THREAD

**Issue by jocacadasi** [GoogleChrome/web.dev#9405]
Hi
In this article
https://web.dev/serve-responsive-images/

It is missing the difference between an image with a specific MIME Type filename vs a different HTTP-header content-type.

I do see many CDN offering images conversion, showing images as doc type in the network tab but the HTTP-header content-type is jpg or image URL with the filename as even like .psd but the HTTP-header content-type is .png or webpp

I would like to understand the difference and what is supported by google and or google images.

What is more critical, the filename or HTTP-header content-type? or do both have to match? Or it doesn't matter. What is the best practice vs multiple browsers or crawl

I'll appreciate all your help.

**Comment by tunetheweb** [comment]
I don't believe that's particularly relevant for that article.

It may be more relevant for the [Image CDNs](https://web.dev/image-cdns/) article though that kind of shows that the file extension requested, may be different to what is delivered. I've added a clarification aside in #9735 

In short the HTTP-header content-type is what matters and the MIME Type filename is only used by web servers to set that type if it's not otherwise provided.
