### ISSUE TITLE
Backend Error

### ISSUE THREAD

**Issue by TomWsl** [GoogleChrome/web.dev#941]
I  put  url  https://www.printingcenterusa.com/printing/business-card-printing  on  https://web.dev/measure  then run audit,  the page result "Backend Error" 
If i run the same url in Chrome Dev Tool can get result.

Please help out,  i am afraid can not get speed score could impact our site's search ranking.

**Comment by robdodson** [comment]
Hey @TomWsl, I haven't had a chance to look at this yet wanted to mention that your score on web.dev does not affect search ranking.

**Comment by robdodson** [comment]
Hey @TomWsl I was able to get a response just now:
![image](https://user-images.githubusercontent.com/1066253/58574068-fe993400-81f3-11e9-8a53-30c76450ea39.png)

Going to close this issue but let me know if you still have problems.

**Comment by roryj-degould** [comment]
Hi @robdodson I notice that the URL you checked is the http version, where the url @TomWsl is having issues with is https. I'm having a similar issue with my site: the http version works, but is essentially testing my IIS not found page because I only run the site at https, while the https version returns this Backend Error with a 400 response.

**Comment by robdodson** [comment]
good point. I just checked his https version and it seems to be working as well.
![image](https://user-images.githubusercontent.com/1066253/58739552-b890cb80-83bf-11e9-9d36-497db579fb2a.png)

@roryj-degould do you have a URL you could share so I could test your site? Very possible that there's something going on with our service that we haven't diagnosed yet.
