### ISSUE TITLE
Virtualize long lists example programs project is broken

### ISSUE THREAD

**Issue by nikoandpiko** [GoogleChrome/web.dev#9618]
**Describe the bug**
First project on this page is broken. https://web.dev/virtualize-long-lists-react-window/

**To Reproduce**
1. Go to https://web.dev/virtualize-long-lists-react-window/
2. Scroll down to the first example 
3. See error

**Expected behavior**
The example should show to demonstrate what the article is describing. 

**Screenshots**
![33E098B9-AB99-4020-B66A-6337782B2A91](https://user-images.githubusercontent.com/54879724/219940310-22830fe8-6de7-4971-8762-3b2be2218431.jpeg)

**Comment by AaronForinton** [comment]
https://glitch.com/~react-window-fixed

@rachelandrew - We have a suspended project here, but looks like the missing embed was a useful example. Wonder if you had any thoughts?

**Comment by rachelandrew** [comment]
@AaronForinton  Houssein is still at Google, so it might be worth reaching out by email. It looks like there are others in a similar state. For example: https://web.dev/precache-with-workbox-react/

Could you check the other pages under https://web.dev/react/ and see how many are broken and linked to Houssein's account, as then we could check in about all of them. These Glitches are problematic because they get tied to a user, unlike the CodePens that we can add to one account.

**Comment by AaronForinton** [comment]
Faulty Glitch embed:

https://web.dev/performance-as-a-default-with-nextjs/

**Comment by nikoandpiko** [comment]
Bumping just in case.

**Comment by dstmarthe** [comment]
We are moving to a new platform and issue tracker, thus I will be closing issues rapidly on GH. All of these are working on my end. If they are not working for you I recommend opening an issue on the new issue tracker at 
https://issuetracker.google.com/issues?q=status:open%20componentid:1400680&s=created_time:desc
