### ISSUE TITLE
Enable tags UI.

### ISSUE THREAD

**Issue by robdodson** [GoogleChrome/web.dev#974]
Clicking a tag should take you to a filtered version of the blog landing page that only shows posts with that tag.

**Comment by robdodson** [comment]
I'd like to revisit the design on this. I like the tags in the sidebar but am not a fan of collapsing them into a drawer on mobile. I feel like that's going to be hard to discover.

**Comment by robdodson** [comment]
Maybe they should move from the sidebar to the footer on mobile?

**Comment by jpmedley** [comment]
+100 on this. WebFu has this ability, which I've used frequently to easily share recent content about specific topics. I've recently learned that the web payment folks have [created a Discuss Group](https://groups.google.com/a/chromium.org/forum/#!forum/paymentrequest) just to share announcements about that topic with partners who have trouble sorting it from our myriad of content channels.

It probably goes without saying that sharing is hard if the filtering isn't reflected in the URL.

**Comment by robdodson** [comment]
It's something I definitely want to do soon. I think the design we have needs some tweaks for mobile so I'm speaking to an agency today about a number of tasks to see if they can help on this.

**Comment by jpmedley** [comment]
I have more information on why we need this. I'm currently interviewing owners and content producers for each of the legacy sites where we distribute Chrome content. My anecdote about web payments illustrates a theme that comes up in almost every interview: the need to send a clear signal to a particular subset of developers. 

Not only would the is feature allow web.dev to serve many existing communication use cases, it would also:
* allow ad-hoc addition of new 'channels' as the need arrises
* provide the ability to monitor web traffic about specific categories of content
* since the channels are essentially ad-hod, allow channels that never require eng effort to shut down if they become moribund.

I want to suggest one feature be added to this ability. Don't just return a list of articles. Create the ability to add introductory text to tag results. For example a url such as web.dev/widgets (where widgets is a tag) would return a page that begins with a paragraph describing widgets before listing the relevant articles. A tag related to a capability could also include [implementation status](https://developers.google.com/web/updates/2018/12/web-share-target#status).

**Comment by robdodson** [comment]
That's a neat idea. I have an agency working on a tags design for us right now so I'll mention this to them.

**Comment by robdodson** [comment]
Here's a high level list of tags that I created based on the ones developers.google.com/web uses. I tried to consolidate things a bit because the one on /web felt very fine grained. There are certainly things missing but i think this will give the folks at Huge a good idea of how many tags we might have for web.dev.

```yaml
---
- 3d
- accessibility
- amp
- analytics
- audio
- augmented-reality
- canvas
- capabilities
- case-study
- cast
- chrome-ux-report
- chrome-dev-summit
- content-security-policy
- cookies
- cors
- css
- devtools
- dom
- encryption
- feature-policy
- file-system
- fonts
- forms
- games
- graphics
- houdini
- identity
- images
- install
- intl
- iot
- javascript
- layout
- lighthouse
- media
- mobile
- modules
- monetization
- network
- node
- notifications
- offline
- origin-trials
- payments
- performance
- permissions
- progressive-web-apps
- puppeteer
- rendering
- security
- seo
- service-worker
- storage
- svg
- testing
- ux
- web-assembly
```

**Comment by jpmedley** [comment]
Looks good.
Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by carolrivero** [comment]
moving to internal tracking
